### ISSUE TITLE
autoFetch option ?

### ISSUE THREAD

**Issue by aboudreault** [dhruvaray/backbone-associations#101]
It would be nice to have some kind of  an autoFetch option in BB-association. I use it with api, and my api is using a lot of references. ie. 

```
{
   title: 'Hello',
   author: user_id
}
```

The author field is a AuthorModel, which also has its own api endpoint. I'm wondering this couldn't be a a feature of the lookup transformation. We should be able to return a promise of something.

@dhruvaray do you think it could be a good addition?

**Comment by dhruvaray** [comment]
It may introduce other complications such as whether the whole graph should be lazily fetched or otherwise... In any case, if you submit a PR, I can definitely take a look to access your idea!

**Comment by aboudreault** [comment]
Yeah. I have been force to do something custom, with sub classing, for that reason.
