### ISSUE TITLE
Passing a function for `collectionType`

### ISSUE THREAD

**Issue by johanneslumpe** [dhruvaray/backbone-associations#102]
I've notived that when we implement `relatedModel` as a function bb-associations will call it to receive the constructor function for the related model:

``` javascript
// Call function if relatedModel is implemented as a function
if (relatedModel && !(relatedModel.prototype instanceof BackboneModel))
    relatedModel = _.isFunction(relatedModel) ?
        relatedModel.call(this, relation, attributes) :
        relatedModel;
```

 If we do the same thing for `collectionType` it is assumed that the function provided is actually already a constructor. First there is only a check whether `collectionType` is a string:

``` javascript
collectionType && _.isString(collectionType) &&
                    (collectionType = map2Scope(collectionType, activationContext));
```

And then the function is automatically treated as constructor function:

``` javascript
 data = collectionType ? new collectionType() : this._createCollection(relatedModel, activationContext);
```

 Is this on purpose or an oversight? It's not an issue to return a new custom instance from the function assigned to `collectionType` but I feel it would be nicer, if both functions were behaving in a unified way. Would be great if someone could shed some light on this.

**Comment by jdkanani** [comment]
`collectionType` should always returns collection constructor. If you need custom instance, use `relatedModel` as function.

`collectionType` is for exceptional condition where you want your own collection class(type) to be initiate as part of nested models. _Why do I ever need this?_  see this explanation https://github.com/dhruvaray/backbone-associations/issues/52

Hope this helps!

**Comment by johanneslumpe** [comment]
@jdkanani that is exactly the point :) I need a custom collection type since my base collection deals with caching of models. Apart from that I like to define custom methods on my collections, too.

I should mention that I develop in node and later pack using browserify. And I am not keen on using a global object. Passing a function to the `collectionType` helps mitigating the need for a global string reference when dealing with circular dependencies. So without using a global object and when having a circular dependency, using the `collectionType` to directly pass in the constructor function instead of a function, which will return the new ctor, is not possible.

It is not a huge issue to return a new object inside the function, but I still think `relatedModel` and `collectionType` should work alike.

**Comment by dhruvaray** [comment]
> > helps mitigating the need for a global string reference when dealing with circular dependencies. 

@johanneslumpe : You may want to see issue #74 and associated recipes. You should not need a global string for resolving circular dependencies!

**Comment by johanneslumpe** [comment]
@dhruvaray Yeah I have seen those recipes and I'm doing exactly that for `relatedModel`s. I am just proposing to change the behavior of `collectionType` to be similar the the behavior of `relatedModel`.  
The recipe uses a string reference in the first example and a function in the second, like this:

``` javascript
relatedModel: function(){ return require("Person");}
```

For a `collectionType` doing this is not possible:

``` javascript
collectionType: function(){ return require("PersonCollection");}
```

because `collectionType` is expected to be either a string, which will resolve to a constructor function on the global object (or the object set in the scope for that matter) or to be a constructor function.
So to achieve a similar behavior to `relatedModel` I have to do this:

``` javascript
collectionType: function(){ return require("PersonCollection")();}
```

Its not a huge issue, but I am suggesting to make this behavior consistent, i.e. have a function for `collectionType` return a constructor function and do not expect it to **be** a constructor function.

Or am I missing something here?

**Comment by jdkanani** [comment]
@johanneslumpe I agree. Will implement it very soon. Thanks.

**Comment by dhruvaray** [comment]
@johanneslumpe : Implemented via commit - 44f1af2a3977c07c1184f482b983e127665a6fbc. Let me know if this works for you.

**Comment by johanneslumpe** [comment]
@dhruvaray I will check it as soon as possible and report back!

**Comment by dhruvaray** [comment]
@johanneslumpe : Here's a test case to get you started:

``` javascript
        var Animal = Backbone.AssociatedModel.extend({
             relations: [
                 {
                     type: Backbone.One,
                     key: 'livesIn',
                     relatedModel: function () {
                         return Zoo;
                     }
                 }
             ]
         });

         var Animals = Backbone.Collection.extend({
             model: Animal
         });

         var Zoo = Backbone.AssociatedModel.extend({
             relations: [
                 {
                     type: Backbone.Many,
                     key: 'animals',
                     collectionType: function () {
                         return Animals;
                     }
                 }
             ]
         });

         var aZoo = new Zoo();
         var animals = new Animals([
             {species: 'fish', livesIn: aZoo},
             {species: 'mamals', livesIn: aZoo}
         ]);
         aZoo.set('animals', animals);
         equal(aZoo.get('animals').models.length, 2);

```

**Comment by johanneslumpe** [comment]
@dhruvaray  haha thanks, but I've got all my stuff already set up :) I just didn't yet have time to change the function I'm passing from returning an instance (to kind of hot fix the old behavior) to returning just the constructor function. But I assume that it will just work fine.

**Comment by johanneslumpe** [comment]
@dhruvaray Mind pushing a patch release to npm? :)

**Comment by dhruvaray** [comment]
Yes... It will go with the next release (soon!) to npm

**Comment by dhruvaray** [comment]
New release out! (and on npm)

**Comment by johanneslumpe** [comment]
:+1:
