### ISSUE TITLE
Parsing on parent's fetch/save; potential inconsistency

### ISSUE THREAD

**Issue by AlexRiedler** [dhruvaray/backbone-associations#103]
In a 1:M relationship, in the initial fetch parse is not ran on the underlying relationship.

e.g. Consider a store with products:
`{ id: 7, products: [6,9,10] }`

the `[6,9,10]` is not parsed and is passed straight into the mapping function provided on the relationship.

However,
if i did something like store.save({'name': 'Jims'}); and the server returned:
`{ id: 7, name: 'Jims', products: [6,9,10] }` products would be subject to parsing on the collectionType it is in (where you should parse the response from the save of the Store, but you should not parse the products -- cause potentially fetching the collection directly has a different parse).

After much painstaking debugging; I am proposing that we add a default relationshipOption of 'parse: false'.

Any input, or discussion before I implement? Alternatively we could document this odd behaviour?

**Comment by dhruvaray** [comment]
@AlexRiedler : Sorry for the delay in reply. 

In Backbone, the call to `set` (in model) and `add` (in collection) is called after the parse operation (if provided). So I am not sure I understand your problem. Would it be possible for you to demonstrate via a test case?

**Comment by AlexRiedler** [comment]
@dhruvaray I think it is cause on initial creation of the collection parse is not called; but on a reset or set it is. I will see if I can get around to writing a test-case for this.

**Comment by dhruvaray** [comment]
If you don't want it to parse, you can always pass in {parse:false} in options - even with the current BB-Associations implementation

``` javascript
relations:[
                {
                    type:Backbone.Many,
                    relatedModel:Product,
                    key:'products',
                    options:{
                        parse:true,
                        add:true
                    }
                }
            ],
```

See this [test case](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L2680-L2738).

**Comment by dhruvaray** [comment]
Did this help?
