### ISSUE TITLE
Explicit belongsTo relationships

### ISSUE THREAD

**Issue by johanneslumpe** [dhruvaray/backbone-associations#104]
Currently I'm using a normal `Backbone.One` relationship for a `belongsTo` relation, even though that's not really correct, since it messes with the `parents` part. Why am I doing this? Consider the following example: We have a model `House` and a model `User`. Each `House` has a relation `ownedBy`, which refers to a `User`. Because of this there will be an entry in the `parents` array of the `User` instance, referring to the `House` model.

It seems a bit odd because of course the house isn't owning the user. How do you approach relations like this? Similar to this or is there a better approach?

**Comment by dhruvaray** [comment]
@johanneslumpe : Sorry for the delay in response. The semantics of `parents` property is purely in terms of the linkages in the object graph. I would not extrapolate any application-level semantics to it.

**Comment by johanneslumpe** [comment]
@dhruvaray Ah ok, then this shouldn't be an issue :) Thanks for clarifying!
