### ISSUE TITLE
No module.exports anymore

### ISSUE THREAD

**Issue by johanneslumpe** [dhruvaray/backbone-associations#108]
With the newest release backbone associations does not export anything anymore (apart from an empty object). What's the reasoning behind this decision?

**Comment by jdkanani** [comment]
Backbone-associations attaches extra properties to Backbone. It is not a module that exports a new object like Backbone does.

That was the reasoning to remove it. On hindsight, for backward compatibility, it may be prudent to keep the old behavior - should some use it as `Backbone = require('backbone-associations)`

We could export `Backbone` OR `Backbone.Associations` (makes more sense?) or an empty object. Any opinions?

**Comment by dhruvaray** [comment]
Pushed out v0.6.1 on npm...
