### ISSUE TITLE
Is there a way to pass options to the related collection?

### ISSUE THREAD

**Issue by janispauls** [dhruvaray/backbone-associations#110]
Like http://backbonerelational.org/#relations-collectionOptions

**Comment by dhruvaray** [comment]
I have just pushed in a commit -  d66904085b89ba8e558358cf958fef7f5332a938 - which will achieve what you want. See the associated test case and let me know if this works for you...

**Comment by dhruvaray** [comment]
Closing this as I am moving the discussion to related issue #109
