### ISSUE TITLE
Bad call to _createCollection

### ISSUE THREAD

**Issue by sdemjanenko** [dhruvaray/backbone-associations#120]
When using the collectionType attribute for a relation the _createCollection is passed the options: {model: undefined}.  The collection I linked to in collectionType already has the model set.  The options then override that model and I get an error.

An ugly fix is:

``` js
data = this._createCollection(collectionType || BackboneCollection,
              relation.collectionOptions || (relatedModel ? {model: relatedModel} : {}));
```

**Comment by dhruvaray** [comment]
This should fix the problem... Let me know if it works for you.
