### ISSUE TITLE
Accessing related model's property in initialize

### ISSUE THREAD

**Issue by sarink** [dhruvaray/backbone-associations#121]
How is one supposed to achieve utilizing a reverse relationship to a parent inside the child's initialize? This is how I've tried to do it...

<pre>
var Store = Backbone.AssociatedModel.extend({
   defaults: {
      some: "stuff"
   },
   relations: [{
      type: Backbone.Many,
      key: "products",
      collectionType: ProductList
   }],
   parse: function(response, options) {
      _.each(response.products, function(p) { p.store = this; }, this);
      return Backbone.AssociatedModel.prototype.parse.call(this, response, options);
   }
});

var ProductList = Backbone.Collection.extend({
   model: Product
});

var Product = Backbone.AssociatedModel.extend({
   initialize: function() {
      alert(this.get("store")); // a valid Backbone.AssociatedModel, but an empty one
      alert(this.get("store").attributes); // empty {}
      alert(this.parents); // empty []
      alert(this.collection.parents); // undefined
   }
});
</pre>

Do I need to do something in ProductList? like have a listener that sets a store to each model in ProductList.add? But even then, ProductList.parents is undefined, so how would I access it?
Is Store.parse() not the place to set this?
If I try setting a reverse Backbone.One relation inside the Product, associations throws an error.
Do I have to wait until after initialize to be able to use the relations? When are they official glued together?
Is this too many questions in a row?

I'm lost.

Thanks! :)

**Comment by dhruvaray** [comment]
The solution seems to be to override the constructor... Seems similar to issue #93. Let me know if that approach works for you?

**Comment by sarink** [comment]
If the related model's attributes are empty inside of initialize, they'll also be empty in the constructor. I'm not trying to set up a listener on the parent, but rather access an attribute of the parent, from within the child's initialize.

something like..

<pre>
var Product = Backbone.AssociatedModel.extend({
   initialize: function() {
      this.get("store").get("state");
   }
});
</pre>

As a workaround, I've done something like this, but it's messy, and I really don't want to have to do it for all the attributes I require..

<pre>
var Store = Backbone.AssociatedModel.extend({
   defaults: {
      state: "MN"
   },
   relations: [{
      type: Backbone.Many,
      key: "products",
      collectionType: ProductList
   }],
   parse: function(response, options) {
      _.each(response.products, function(p) { p.storesState = response.state; }, this);
      return Backbone.AssociatedModel.prototype.parse.call(this, response, options);
   }
});
var Product = Backbone.AssociatedModel.extend({
   initialize: function() {
      this.get("storesState");
   }
});
</pre>

Is there some other way, or have I misunderstood?

**Comment by sarink** [comment]
OK, a child not being able to read its parents attributes.... I find it hard to believe that this is a missing feature, but I really cannot figure out how to do it.

This is supported, right? How?!

**Comment by dhruvaray** [comment]
@sarink : Was caught up with other things... I had a look at your example. 

You can achieve what you want with the code snippet below

``` javascript
var ProductList = Backbone.Collection.extend({
    model: Product
});

var Product = Backbone.AssociatedModel.extend({
    initialize:function(){
        equal(this.collection.parents.length,1); //1
         //Has store instance at location 0
        equal(this.collection.parents[0] instanceof Store,true); 
    }
});


var Store = Backbone.AssociatedModel.extend({
    defaults: {
        state: "MN"
    },
    relations: [{
        type: Backbone.Many,
        key: "products",
        collectionType: ProductList
    }]

});

var plist = new ProductList;
var s = new Store({products:plist});
var p = new Product({type:'shoe',name:'puma'},{collection:plist});
```

**Comment by sarink** [comment]
@dhruvaray, what if the products are fetch()ed with the store?

<pre>
var store = new Store();
store.fetch() // response: {id: 1, state: "MN", products: [{id: 1, name: "Capn Crunch"}, {...}] }
</pre>

In this case, the backwards relationship to go from a product to its store must happen in Store.parse, as in my original example. And then, product.parents[0] = store, BUT it is an empty store (the original problem). I don't really see how you've solved it?

**Comment by dhruvaray** [comment]
For the fetch scenario, you can make it work like this

``` javascript
var Product = Backbone.AssociatedModel.extend({
    initialize: function () {
        equal(this.collection.parents.length, 1);
        equal(this.collection.parents[0] instanceof Store, true);
    }

});

var ProductList = Backbone.Collection.extend({
    model:Product
});


var Store = Backbone.AssociatedModel.extend({

    relations: [
        {
            type: Backbone.Many,
            key: "products",
            collectionType: ProductList
        }
    ],
    //Simulate a network call
    sync:function (method, model, options) {
        return options.success.call(this,{
                state: "MN",
                id:"1",
                products: [{id : "1", name: "Capn Crunch"}]
        }, options);
    }

});

var s = new Store({products:[]); //workaround to get parents in initialize
s.fetch();

```

**Comment by dhruvaray** [comment]
Also, the traversal is built via a depth-first traversal, so you may not have parent's completely built up in a child's initialize/constructor. Can you also elaborate on what you are trying to achieve? Maybe there is an alternative?

**Comment by sarink** [comment]
Let's say, for example...

If the store is in state "NY", then a product should append its calories to its name.

So Product.initialize would look like

<pre>
if (this.get("store").get("state") === "NY") this.set("name", this.get("name") + " - " + this.get("calories");
</pre>

Perhaps you'd argue this logic is OK to be placed inside ProductView, or even in the view's template. But let's say you've architected your app to use a viewmodel approach. In this case, you'd need a model to hold the string that the view is going to display, rather than have the logic in the view.

Either way, I think the problem still fundamentally exists: You never know for sure when these related models will be built up, and when they won't be.

So.. Is there any way to know? Interested to hear your ideas on the subject

FYI, I do understand the complexities of this problem. After struggling with backbone-relational, hating backbone.supermodel, and before finding backbone-associations, I actually started writing my own relational library.  My approach to get around this problem was simply that at each level where this was necessary, the developer was to write a "load" function on the parent object that would basically be a series of chained fetch()es and .then()s to ensure the order was correct. It was unfortunate that the library could not abstract this, so I also had experimented with every model setting up callbacks and events on anything that was related so that you could always know when property X was set or not, but it became messy and I never had time to finish it.

**Comment by dhruvaray** [comment]
Given our depth-first traversal, your specific use case can be modeled much more easily. See the snippet below.

``` javascript
var Product = Backbone.AssociatedModel.extend({
});

var Store = Backbone.AssociatedModel.extend({

    relations: [
        {
            type: Backbone.Many,
            key: "products",
            relatedModel: Product
        }
    ],
    //Simulate a network call
    sync:function (method, model, options) {
        return options.success.call(this,{
            state: "NY",
            id:"1",
            products: [{id : "1", name: "Capn Crunch", calories: '20mg'}]
        }, options);
    },

    initialize : function(){
        this.on('change:state',function(){

           if (this.get('state') == 'NY')
               this.get('products').each(function(product){
                   product.set('name', product.get('name')+'-'+product.get('calories'))
               })
        })

    }

});

var s = new Store();
s.fetch();

equal(s.get('products').at(0).get('name'),'Capn Crunch-20mg'); //Hurrah!

```

What do you think?

PS: 
- I would also like to retain the logic in the model (if possible) than the view.
- Generally speaking, you would **have** to put a listener in for the change in `state` attribute. A one-time processing of state change in `initialize` also will not cut it.

**Comment by sarink** [comment]
Doing it that way is alright, but... It really _should_ be the Product model's job itself to do such a thing, rather than having the logic live in the parent Store model. Don't you think?

Consider a case where the logic is more complex? Maybe the value of name now depends on store.state, as well as a property of one of the products children? Or even a grandchild's property? ...

It just seems like having this logic in the Store's initialize is a bit hacky.

**Comment by jdkanani** [comment]
@sarink That's right. What do you suggest to solve this problem? Any idea?

**Comment by sarink** [comment]
I've thought a bit about this, but not too hard, so that's my disclaimer in case these suck:
1. Somehow force the developer to define the order that models should be initialized. I'm not sure of a pretty/clean/nice high-level way to represent this, though.
2. Have every AssociatedModel trigger a generic catch-all "setupComplete" event, or something similar. Devs would simply write any dependent code such as this inside this callback. It would be nicer than having to do it on a per-attribute basis.
3. The hackiest, although perhaps the coolest in terms of abstraction it offers... Since Store.parse occurs before Product.initialize, I wonder if you could set a bunch of "hidden" properties on the model, and when trying to get() a property that has not been set up yet, it could fall back to this "hidden" cache to retrieve the value. Maybe do this in AssociatedModel.constructor, where you've got all your own attributes, you know what relations you have, and since its depth-first you know what has been set up and what hasn't?

There's some fairly obvious and gigantic hurdles with each of these, but I think a clean solution to this is necessary for this library. It's something I personally find myself needing rather frequently.

**Comment by jdkanani** [comment]
1. Not sure how to do so
2. I found more appropriate. We can make it as method instead of event. 
3. Magical but tricky.

@dhruvaray what do you think?

**Comment by sarink** [comment]
(My own opinions:
1. Don't really like it, just threw it out there
2. Straight forward, probably not too hard. A decent solution.
3. My personal favorite. But definitely tricky, yes.)

**Comment by dhruvaray** [comment]
At this point, I'd love nothing more than a magical PR ;) 

Jokes apart, What do you guys think of this?

I set the parent early enough (before the values are assigned to the model or collection). So `parents` would always be guaranteed to be present in `initialize`. Then the `Product` model would look like

``` javascript
var Product = Backbone.AssociatedModel.extend({
    initialize : function(){
        var parent = this.collection.parents[0];
        parent.on('change:state',function(model, value, options){
           if (value == 'NY')
               this.set('name', this.get('name')+'-'+this.get('calories'));
        },this)
    }
});
```

**Comment by dhruvaray** [comment]
I just made some minor changes to support this scenario. Here's a working [test case](https://github.com/dhruvaray/backbone-associations/commit/1eaa56876e21c85fecc9e1dea9a231c557f153ed#diff-470ce3d8e231803affbdab621a95e1e2R1699) which demonstrates this.

**Comment by sarink** [comment]
The only issue I have with that solution is that it becomes quite an annoyance if you have to do it for multiple attributes. Also think about the views, how many re-renders must they undergo? What if you're dependent upon a grandparent's property? This gets messy quick.

It just seems like since the information IS actually present beforehand, that it could be done without any change listeners.

**Comment by dhruvaray** [comment]
> > if you have to do it for multiple attributes.

You would have to make a check for multiple attribute values **even** in  your approach.

> > What if you're dependent upon a grandparent's property

That problem(?) does not go away even with the approaches you suggest. If you need to look up two levels, you always have to do that.

> > think about the views, how many re-renders must they undergo?

The moment a value is  `set` - irrespective - of whether you do it via a change event _OR_ directly (in initialize), who-ever is listening to those changes will get notified/views re-render etc. (the option to leverage `options.silent` is always available) In fact - with the change listener - I would argue that there is a **guarantee** that whenever the parent attribute changes, child attribute values are in sync with the business logic. Not so in the direct approach.

**Comment by sarink** [comment]
Multiple attributes = multiple change listeners = multiple changes = multiple renders. If you instead set the value inside parse or initialize, there is no "set" event. The model simply gets instantiated with the value you desire. You can't create a view for a model that doesn't exist yet (and as soon as you create it, it will run initialize, and have the proper value. Nothing will ever see the old value). Nothing is listening to a model that hasn't even been initialized yet?

I don't think I understand why you say that setting it initialize is no different than a change listener. Because they seem very different to me?

In the case where the attribute could change, then you're right. But in this case you'd of course want a change listener - wouldn't backbone-assocations have always and already handled this? The whole point was to not have to set up a change listener for every attribute you need.

I guess I am describing a use case where the related model's attribute will not change (the Store isn't going to just jump states) - so setting up a listener seems like an unnecessary hassle. Especially when the value is ALREADY KNOWN and is there before Product.initialize ever gets fired...

If you want to get a value, you should be able to get it. If you want to monitor when a value has changed, you should be able to do that too. But they are separate things and do not always overlap.

**Comment by dhruvaray** [comment]
In which case, you can get what you want easily by an override of `parse` on the `Store` model

``` javascript

    // In `Store` model definition
    parse:function(response,options){
        var state = response.state
        _.each(response.products, function(p) {
            if (state = 'NY')
                p.name = p.name + '-' + p.calories
        });
        return response;
    }

```

**Comment by sarink** [comment]
We've been over this one... It works, it's just conceptually bad. It's not the Store's job to change the Product's name. That logic ought to live within the Product.

**Comment by dhruvaray** [comment]
I'm afraid a framework level solution seems to elude me. Please do submit a PR if you find a generic enough approach. I will be glad to take a look

**Comment by dhruvaray** [comment]
This commit gives you exactly what you want... The test case is [here](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L1699-L1750).

It implements suggestion # 3. (The most magical one :)) I am not sure about the side effects on the `validate` method. Any thoughts? Also extra test cases would always be welcome!

**Comment by sarink** [comment]
What are the potential issues you see regarding `validate`? I don't think I follow

BTW, I think I found a typo in your implementation

**Comment by dhruvaray** [comment]
We are accessing parent attributes (in the children) before the parent `set`. Consequently, it is possible that the parent `validate` may throw an exception. I am not sure how to handle that in the children when it happens. 

Also it appears that `previousAttributes`/`hasChanged` etc may be broken with this change - during the **construction** phase. So `initialize` will not return the right values if these properties are queried in the `initialize` method.

**Comment by sarink** [comment]
Isn't the `_set` (where the cache is created) only getting called from the constructor? Can you pass `options:{validate:true}`  to the constructor? And by default `validate` only runs on `save` ... Am I missing something?

`previousAttributes/hasChanged` - is the problem with the parent (Store) or child (Product)?

**Comment by dhruvaray** [comment]
> > previousAttributes/hasChanged - is the problem with the parent (Store) or child (Product)?

parent - Store. (General case is whenever the cache is used)

**Comment by sarink** [comment]
If you restrict the cache to only being created in the constructor, before the model has been "set up", you can ensure that nobody has called `validate`. Then, if you delete it after this, you can ensure that `previousAttributes` can't be out of sync.

The only time the cache is used is BEFORE the model has finished `parse` (for the first time), so any `previousAttributes` would obviously just be empty, and nobody's run `validate` on these empty attributes. Right?

**Comment by dhruvaray** [comment]
Yes... For the constructor case, it will be consistent. But it will break if we try to set a different object graph at a later stage.

``` javascript

var s = new Store();
s.fetch();

s.set({state: "NY", id:"1", products: [{id : "2", name: "Capn Crunch 2"});
```

**Comment by spencercarnage** [comment]
I'm running into an issue where `parents` is only defined in the `initialize` function when I use a `setTimeout` with 0ms on a `Backbone.Many` relationship.

```
var Location = Backbone.AssociatedModel.extend({
    defaults: {
        add1: "",
        add2: null,
        zip: "",
        state: ""
    },
    initialize: function () {
        var self = this;
        console.log(typeof this.collection.parents !== 'undefined');

        setTimeout(function () {
            console.log(typeof self.collection.parents !== 'undefined');
        }, 0);
    }
});

var Project = Backbone.AssociatedModel.extend({
    relations: [{
        type: Backbone.Many, //nature of the relation
        key: 'locations', //attribute of Project
        relatedModel: Location //AssociatedModel for attribute key
    }],
    defaults: {
        name: "",
        number: 0,
        locations: []
    }
});

var project1 = new Project({
    locations: [{
        name: 'Hawaii'
    }, {
        name: 'Los Angeles'
    }]
});
```

[Here's a JSFiddle where you can see it in action.](http://jsfiddle.net/spencercarnage/eUntR/2/)

**Comment by sarink** [comment]
Is this with the latest github source?

**Comment by spencercarnage** [comment]
The JSFiddle is using `0.6.1` which I'm getting from the CloudFlare cdn, [http://cdnjs.cloudflare.com/ajax/libs/backbone-associations/0.6.1/backbone-associations-min.js](http://cdnjs.cloudflare.com/ajax/libs/backbone-associations/0.6.1/backbone-associations-min.js)

**Comment by dhruvaray** [comment]
@spencercarnage : This should work on the master or the upcoming 0.6.2 release.
