### ISSUE TITLE
0.6.2 ETA

### ISSUE THREAD

**Issue by chiplay** [dhruvaray/backbone-associations#123]
Hey @dhruvaray - looking forward to using some of the updates that have been added to master recently but I'd perfer to wait until it gets tagged for our bower setup.  Any ideas when you think the next release will happen?  Thanks!

**Comment by dhruvaray** [comment]
Hopefully this weekend!

**Comment by dhruvaray** [comment]
@chiplay : I am targeting March 29 to pull in two other features. Just FYI

**Comment by dhruvaray** [comment]
@chiplay : Finally out!
