### ISSUE TITLE
Why must my child be an AssociatedModel in 1:1

### ISSUE THREAD

**Issue by fenduru** [dhruvaray/backbone-associations#124]
When creating an AssociatedModel, specifying a Backbone.Model as the relatedModel gives an error, but its okay to specify a normal Backbone.Collection for 1:M. What's the reasoning here? It makes it hard for me to use Associations in an ecosystem where I don't have control of all of the models I'm using

**Comment by dhruvaray** [comment]
A collection by default is a container for many models. So there was no reason to specialize it. But `AssociatedModel` forms the basis for specifying the nature of relationships (1:1 and 1:M) with it's children (and their type too). Without that supplement, it would be difficult to infer types and the nature of the relationships. That being said, if you have any alternative ways, we could handle it, I would be glad to hear. (with a PR hopefully :))

**Comment by fenduru** [comment]
I understand the need for AssociatedModel in general, but what I am asking is why I can't have an AssociatedModel that has 1 Backbone.Model? If there is no technical reason for this I'll gladly submit a PR, but wanted to be sure first.

**Comment by dhruvaray** [comment]
I am not sure I follow you. Can you put out some pseudo code on what you are trying to achieve?

**Comment by fenduru** [comment]
http://jsfiddle.net/2F65W/

**Comment by dhruvaray** [comment]
Ok... But I suspect that this would be useful in only in a limited scenarios (leaf level of the graph only).A PR with a test case would be appreciated!

**Comment by fenduru** [comment]
Gladly. Only thing is I'm running into some odd behavior in the test suite.

```
ChildModel.prototype instanceof Backbone.AssociatedModel
```

is returning true in the test suite, but is false in reality, so I can't get my tests to fail.

**Comment by dhruvaray** [comment]
That may be because of environment.js... You may have to use [Backbone.OriginalModel](https://github.com/dhruvaray/backbone-associations/blob/master/test/backbone/environment.js#L34)

**Comment by jdkanani** [comment]
@fenduru @dhruvaray It was supported [before v0.5.2](https://github.com/dhruvaray/backbone-associations/compare/v0.5.1...v0.5.2#diff-3336e14dadeb5f8353ac7e5f5ebb571cR204). I am not sure why we removed it. But of course adding it back would be great.

**Comment by dhruvaray** [comment]
@fenduru : I didn't hear back from you. So I made the changes. You should now be able to set the `relatedModel` to plain 'ol `Backbone.Models` as well. See the test case [here](https://github.com/dhruvaray/backbone-associations/commit/455653b2f4e59738cb1eb46502d51d8d7972b290#diff-470ce3d8e231803affbdab621a95e1e2R1699)  and [here](https://github.com/dhruvaray/backbone-associations/commit/799a224f7ee7bec5bd089cce0c3501b1c0a50fb7#diff-470ce3d8e231803affbdab621a95e1e2L1699).

**Comment by fenduru** [comment]
@dhruvaray had a busy week so didn't get a chance to look into this. Thank you so much for doing this though! Much appreciated.

Looked at the test case, and it seems a little bit weird to do

```
Backbone.AssociatedModel = Backbone.Model;
Backbone.Model = Backbone.OriginalModel;
```

Inside a test case. Would it make sense to isolate the environment.js test, and have the AssociatedModel tests use Backbone.AssociatedModel and Backbone.Model as they would be used in the wild?

**Comment by dhruvaray** [comment]
That's because in environment.js, we set Backbone.Model to AssociatedModel to run all Backbone library tests with AssociatedModel. This test case is an exception so that decision needs to be overridden.
