### ISSUE TITLE
preventing relations key from being stored on AssociatedModel

### ISSUE THREAD

**Issue by gr2m** [dhruvaray/backbone-associations#127]
I've a Meeting & a Minute model, as well as a MinutesCollection. Here's my setup, everything works great so far.

``` js
var Model = BackboneAssociations.AssociatedModel.extend({
  type: 'meeting',
  relations: [
    {
      type: BackboneAssociations.Many,
      key: 'minutes',
      collectionType: MinutesCollection,
      relatedModel: Minute
    }
  ]
});
```

On save, I'd not like a meeting model to store the minutes as a property, as I store them separately. I achieve that currently by overiding the `toJSON()` method like so:

``` js
  toJSON: function() {
    var attributes = _.clone(this.attributes);
    delete attributes.minutes;
    return attributes;
  },
```

That works, but I just want to make double sure that this is the right way to do it and that there are no side effects

**Comment by dhruvaray** [comment]
Nothing wrong with what you are doing, but you can do it far more easily like this

``` javascript

var MeetingModel = Backbone.AssociatedModel.extend({
  relations: [
    {
      type: Backbone.Many,
      key: 'minutes',
      collectionType: MinutesCollection,
      isTransient : true // Will not serialize `minutes` on `save`
    }
  ]
});
```

**Comment by gr2m** [comment]
that's what I was looking for, most excellent! Thanks a lot, Dhruva!
