### ISSUE TITLE
triggering change events for associated models with fetch()

### ISSUE THREAD

**Issue by donnut** [dhruvaray/backbone-associations#13]
I've a simplified model with three levels of 1-to-many relations: webapp, panel and master. 
Using a server call (mocked in the example) I'm successfully able to load and instantiate the models.

The main view is instantiated before the fetch and associated with the main model (webapp). All other views are instantiated and associated in the parent views. 

The example is here: https://gist.github.com/3974610

My problem is that the change events of the related models are not triggered. I'm sure I'm doing something wrong here but I'm unable to find my mistake. 

Any help is appreciated.

**Comment by jdkanani** [comment]
`change:panel` is triggered only if reference of object has changed.
As `panel` is a collection so you can bind your events accordingly -

Check this out - https://gist.github.com/3974610#gistcomment-591058

**Comment by donnut** [comment]
Thanks for the comprehensive answer. Unfortunately, only the webappView and panelView are rendered. For some reason the panel associated with master does not receive a reset event:

```
this.model.get('master').on('reset', this.render_master)
```

render_master is never called.

I've added an extra event to PanelView:

```
this.model.get('master').on('add', this.render_one_master)
```

When adding a master object:

```
var mast = new Master({ name: 'new one' });
webapp.get('panel').at(0).get('master').add([mast]);
```

render_one_master() is called.
This means that the events are properly connected to the master models, but for some reason the reset event on the master collection is not triggered by fetch()

**Comment by jdkanani** [comment]
`initialize` of `PanelView` will bind `reset` on `master` after data (which you are fetching) set to model.

**Comment by donnut** [comment]
Yes, so you mean that the `reset` event of `master` is not triggered because it is set after the data is fetched? What is your suggestion to solve this? Should I trigger a `reset` on `master` manually? I've tried:

`webapp.get('panel').reset()` and `webapp.get('panel').at(0).get('master').reset()`

but that doesn't have any effect. Any thoughts?

**Comment by jdkanani** [comment]
You can always use `masterCollection.trigger("reset")` explicitly or execute`render_master` from `PanelView` render.
