### ISSUE TITLE
Collections not in global scope throwing undefined.

### ISSUE THREAD

**Issue by ghost** [dhruvaray/backbone-associations#136]
For collections defined as strings, Line 758 in map2Scope returns target, but if the target is defined using scopes (ie appears in scopes[i] where i> 0) target can be undefined.

I think the fix is:
if (typeof target !== "undefined" && target) break;

FYI
Thanks for a great library.  Martin.

**Comment by dhruvaray** [comment]
@mrcfisher  : Thanks for the appreciation! 

It would be nice if you can submit a PR with the fix and the test case. I will be more than happy to merge!
