### ISSUE TITLE
"change:'child_model'" event not firing

### ISSUE THREAD

**Issue by romanenko** [dhruvaray/backbone-associations#14]
Hello. I'm using your great backbone-relations implementation in a project with a music player, which can play musical albums with tracks.

I have a Player model with a child album:

```
class App.Models.Player extends Backbone.AssociatedModel
  relations: [
    type: Backbone.One
    key: 'album'
    relatedModel:'App.Models.Album'
  ]

  defaults:
    album: null
    current_track: null
    pending: null

  ........
```

And in AlbumView I create a new player instance if no any, or update album attribute with a new album:

```
class App.Views.Albums.AlbumView extends Backbone.View
  events: {
    "click .cover": "load"
  }

  load: ->
    if App.PlayerView
      App.PlayerView.model.set "album", @model
      console.log "New album: #{App.PlayerView.model.get('album').get('title')}"
    else
      player = new App.Models.Player({album: @model})
      App.PlayerView = new App.Views.Player.PlayerView({model: player})
      $('#player_box').html(App.PlayerView.render().el)
      player.on "change:album", ->
        console.log "Album changed"
    .....
```

When a new album cover is clicked console shows a message with a new album title, but `"change:album"` event does not trigger. Strange, but when I change my code to `player.on "change"` it fires when the album is changed.

**Comment by dhruvaray** [comment]
Great to hear that the library is useful for your work! This bug is now fixed on the latest. We also have now introduced fully qualified paths in the event names... The documentation will be updated soon to reflect the new changes.
