### ISSUE TITLE
Custom events triggered by models inside a collection

### ISSUE THREAD

**Issue by atomictag** [dhruvaray/backbone-associations#142]
I am having some troubles in getting custom events (= issued with `model.trigger(...)`) from models inside a collection to fire with the expected event path. The scenario is very simple: an AssociatedModel contains a collection, the collection contains only one model and a custom event is triggered by that model. Just like change events are in the form `change:<collection_key>[model_index]`I would expect my `custom_event` to be issued as `custom_event:<collection_key>[index]`, but that does not seem to be the case (only the event `custom_event:<collection_key>` is recorded. Example below:

```
var Thing = Backbone.AssociatedModel.extend({});

var Things = Backbone.Collection.extend({
    model : Thing
});

var StuffModel = Backbone.AssociatedModel.extend({
    relations : [{
        type : Backbone.Many,
        key  : 'things',
        collectionType : Things
    }],
    defaults : {
        things : [ {} ]
    }
});

var stuff = new StuffModel;
stuff.on('custom_event:things', function() {
    // this WILL be called
});
stuff.on('custom_event:things[0]', function() {
    // this WILL NOT be called
});
stuff.get('things[0]').on('custom_event', function() {
    // this WILL be called, but of course it works only if 'things[0]' exists
    // when the listener is bound to the event 
});

// Trigger a custom event. Expected event handlers to fire:
// - custom_event:things[0]   
// - custom_event:things   
stuff.get('things[0]').trigger('custom_event');

// Note that stuff.get('things[0]').set({ type : 'junk' }) correctly triggers
// the change event 'change:things[0]'
```

Did I miss anything important on how custom events are propagated in a Backbone/Backbone.Associations setup?

Thanks in advance and keep up with your great job!

**Comment by dhruvaray** [comment]
@atomictag : Thanks! And hello again :)

Typically when you do this, you need to specify trigger arguments. This will tell BB-Associations which element of the collection has changed. Without this info, it is impossible to compute the index of the collection which has triggered the change. So your trigger code should change to  look like

``` javascript
stuff.get('things[0]').trigger('custom_event',stuff.get('things[0]'));

//and
stuff.on('custom_event:things', function(obj) {
  //obj will tell you which model in the collection has changed.
});
```

The behavior is same for BB events like `add`, `remove` etc.

The BB `change` event is little different. 

BB throws 2 events whenever an object attribute in a collection is updated. There is a `change` and `change:attribute`. Also, it make sense to do something like `change:dependents[0].age`. The semantics of `change` makes sense to say that a particular object's attribute has changed.

However, it is difficult to conceptualize the behavior for other BB events (as well as custom events). Like add:dependents[0] would make less sense (in IMO) than add:dependents and pass the added dependent as a parameter. Similarly for custom events. 

The code therefore checks specially for `change` events to allow the slightly different behavior. That is why users can specify the index of the changed object in the collection. 

Hope that makes it clear.

**Comment by atomictag** [comment]
Thanks for that. I should have thought about the symmetry with 'add', 'remove' etc. - where it all makes sense. However I find this less intuitive with custom events or built-in events like 'sync' - which, for example, gets triggered when a collection is fetched as well as when each of its instance models is fetched. `sync:collection[0]` would make the event unambiguous (`sync` here is clearly triggered by the instance). I suppose a nice-to-have would be to preserve the current behaviour and fire an additional generic, un-indexed `sync:collection[*]` to mark the event as "triggered by a model within the collection", provided EVENTS_WILDCARD is set (although the difference with `sync:collection` is minimal and it might even make things confusing...).

Many thanks!

**Comment by dhruvaray** [comment]
This can be easily made into a user-configurable entity. For example, if you want that behavior for custom_event, change [line](https://github.com/dhruvaray/backbone-associations/blob/master/backbone-associations.js#L381) to eventType === "change" || "custom_event". Also, don't forget to throw the object which has triggered the custom event in the collection.

``` javascript
stuff.get('things[0]').trigger('custom_event',stuff.get('things[0]'));
```

**Comment by atomictag** [comment]
Great, thanks for the tip! 

I would advance the suggestion that the default behaviour could be extended to support `sync` (which by contract has the object which triggered the sync event as first parameter) alongside `change` as it is right now. Custom events are relatively less frequently used than the BB built-in ones - and I see a good case for `sync` events to use the fully-qualified path of the object that got sync'd.

Thanks again

**Comment by dhruvaray** [comment]
Thanks! Yes... Tagging this as an enhancement for sync as well as the possibility of users defining the behavior for custom event paths externally.
