### ISSUE TITLE
Load Order if not using requirejs / tech like that

### ISSUE THREAD

**Issue by rstudner** [dhruvaray/backbone-associations#157]
So, new to using backbone associations but i'm sure i'm stumbling on 'rookie problem #1'

Basically, I have to specify models in _precisely the right order_ or I can use relatedModel (for things that aren't defined on the page yet).

Basically does this mean -- until I can get a giant legacy app converted over to requirejs/browserify or something -- that I have to make a single backboneModels.js file, that has literally all my models in exactly the right order :)?

Say it ain't so!

**Comment by jameslai** [comment]
Yes.
