### ISSUE TITLE
How to use backbone-associations in browserify ?

### ISSUE THREAD

**Issue by davvdg** [dhruvaray/backbone-associations#162]
Hi !

I can't figure out how to use backbone-association in browserify.

I tried:
 var Backbone = require("backbone");
 var Association = require("backbone-associations");
var MyModel = Backbone.AssociatedModel.extend({
...
});

but the browser crashed saying 

Uncaught RangeError: Maximum call stack size exceeded

and effectively, the call stack looks like:
Backbone.AssociatedModel.Backbone.Associations.AssociatedModel.BackboneModel.extend._set

which looks like a bit too much "AssociatedModel" in the same line...

Any help (or a browserify recipe) appreciated

Best regards

David

**Comment by skysteve** [comment]
Not sure if you've solved it by now but I'm doing the following

```
var Backbone = require('backbone-associations'),
    _ = require('underscore')._

module.exports = Backbone.AssociatedModel.extend({
....
})
```

**Comment by jameslai** [comment]
Backbone Associations already works with Browserify and Webpack. There is a cyclic dependency somewhere in your code.
