### ISSUE TITLE
Saving child of Model in Collection result in improper overwrite on return

### ISSUE THREAD

**Issue by christophermina** [dhruvaray/backbone-associations#17]
I have a collection of models, each model has a one-to-one mapping with a child.  

An editor is used to modify the child object and save it, upon success, the _byID property on the collection gets modified such that the child becomes the collection object, instead of remaining on as a child.  

For instance - in pseudo code

``` javascript

var collection = Backbone.Collection.extend({
    model : Parent
})


Parent = {
    relations : [
            {
                type : Backbone.One,
                key : "child",
                relatedModel : Child
            }
        ]   

    Career : "",
    Address: "",
    child : null
}


Child = {
  FavoriteToy: "",
  Color: ""
}


/// Make test call to get parent:
collection.get(1); ///  returns the appropriate parent

function : updateAndSaveChild(){
    parent.get("child").set({ color : blue})

    parent.get("child").save({
        success : function(){

            ///  Make test call to get parent
            collection.get(1); ///  returns the CHILD object.
        }
    })
}
```

Upon inspection, the raw collection is in tact (collection.models), but the _byID object has been replaced.

I've stepped through and found this occurring in the Collection.OnModelEvent function:

``` javascript
 _onModelEvent: function(event, model, collection, options) {
      if ((event == 'add' || event == 'remove') && collection != this) return;
      if (event == 'destroy') {
        this.remove(model, options);
      }
      if (model && event === 'change:' + model.idAttribute) {
        delete this._byId[model.previous(model.idAttribute)];
        this._byId[model.id] = model;
      }
      this.trigger.apply(this, arguments);
    }
```

passing {silent : true} as an option fixes the problem.

**Comment by jdkanani** [comment]
I don't know if I understood you correctly but I think latest `master` branch has fix for the same you are looking for. (It should be v0.2.0 you are working on) - it was the problem with same `PropertyName` in nested models.
So, change  in `child`'s property `x` made `parent`confused by triggering `change:x` event on `parent` object (by bubbling up events).

`change:id` event bubbles up to top of model - here collection, and calls `_onModelEvent`. And thus, we can understand the consequences.

``` javascript
if (model && event === 'change:' + model.idAttribute) { // parent && event == "change:id"
        delete this._byId[model.previous(model.idAttribute)];
        this._byId[model.id] = model;  // collection._byId[1] = childModel
}
```

You can compare e82c454c3392de166e7833c8fc7f7bafb22aba97 and http://jsfiddle.net/jdkanani/tGXqC/, and verify problem.

Introducing notion of eventPath like `parent.child.id`, resolves the problem on latest.
