### ISSUE TITLE
Issue using Backbone.AssociatedModel with CoffeeScript 'extends' keyword

### ISSUE THREAD

**Issue by cebartling** [dhruvaray/backbone-associations#20]
Tried to use this framework using the standard way of extending in CoffeeScript:

``` coffeescript
class MyAssociatedModel extends Backbone.AssociatedModel
...
```

When I started to use the new models in some Jasmine tests, I received all sorts of errors.  

When I use the form:

``` coffeescript
MyAssociatedModel = Backbone.AssociatedModel.extend {
...
}
```

This form seems to work.  Is there something happening the extend function that isn't getting called when using CoffeeScript class extension?

**Comment by dhruvaray** [comment]
I haven't really worked in coffeescript. But I picked up some coffeescript syntax since the issue you filed yesterday. Here is a [jsfiddle](http://jsfiddle.net/dhruvaray/scb4T/) which shows backbone-associations working with coffeescript.

**Comment by dhruvaray** [comment]
It works with jasmine as well. I have forked the try-jasmine repository to add backbone-association dependencies. Clone this [repository](https://github.com/dhruvaray/try-jasmine). After cloning, on your local machine, open up /public/index.html in a browser. 

Paste this coffeescript code in the source window.

``` coffeescript
  window.app = {}

  class app.Location extends Backbone.AssociatedModel
    defaults:
     add1: ''
     add2: ''
     zip: ''
     state: ''

  class app.Project extends Backbone.AssociatedModel
    defaults:
     name: ''
     number: 0
     locations: []

    relations: [
     type: Backbone.Many
     key:  'locations'
     relatedModel:app.Location
    ]

  p = new app.Project
  l = new app.Location add1:"P.O Box 3899", zip:"94404", state:"CA"

  p.get('locations').add l
```

Paste this in the specs window.

``` coffeescript
describe "p", ->
  it "is at zip 94404", ->
    expect(p.get('locations').at(0).get 'zip').toBe "94404"
```

You will see the specs passing.

![jasmine](https://f.cloud.github.com/assets/2075506/92836/8eb9a714-65f8-11e2-8342-56b73f3cbed3.png)

It appears to be a configuration or setup issue on your system.

**Comment by dhruvaray** [comment]
I made it a bit easier for you to experiment without downloading/installing anything. Go to this [link](http://dhruvaray.github.com/try-jasmine/public/index.html) and copy the code snippets from the earlier comment to see backbone-associations working with Jasmine
