### ISSUE TITLE
AMD support and bower registry

### ISSUE THREAD

**Issue by exceedhl** [dhruvaray/backbone-associations#21]
Hi, 

Could you add AMD support and register it in the bower repository? It would be very handy for web developers.

**Comment by dhruvaray** [comment]
Now registered in bower registry...

**Comment by brianjmiller** [comment]
+1 to this. Minimally 'module.exports' needs to be checked for definition first it seems. I'm new to this particular module and module world but I'm trying to use almond.js and it is blowing up with "Uncaught ReferenceError: module is not defined". Adding the following "fixes" it but not sure what it might break:

```
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
    exports = module.exports = Backbone;
}
```

Presumably to make it AMD based a define call should be added.

(Commenting in case someone else comes across this.)

**Comment by jdkanani** [comment]
@brianjmiller I agree with your code snippet. I think you are using v0.4.2,  edge version has a fix 47a4df7ebc8748d1c8b2a413c72c65f389bc2659 for that.

To use backbone-associations as AMD module you should use specific `shim-config` for your application.
Here is the example you can refer to: https://gist.github.com/jdkanani/5256463

**Comment by koenHuybrechts** [comment]
Maybe also subscribe to Jam package manager? jamjs.org

**Comment by dhruvaray** [comment]
v0.5.0 is now part of Jam package manager...

**Comment by willgm** [comment]
I'm using the backbone-associations on a big project, which is already in development for two years, and we are close to the 1.0 version, but we are having trouble to generate the final script bundle file with requirejs, even with the shim configuration there is a "uncaught typeerror: cannot read property 'Model' of undefined". We are having this type of error with all the backbone plugins that don't have an amd version. Isn't possible to generate one?
