### ISSUE TITLE
npm package does not have "	"backbone.associations"?

### ISSUE THREAD

**Issue by exceedhl** [dhruvaray/backbone-associations#22]
Trying to npm install backbone.associations, but got this: 

npm http GET https://registry.npmjs.org/backbone.associations
npm http 404 https://registry.npmjs.org/backbone.associations
npm ERR! 404 'backbone.associations' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by dhruvaray** [comment]
Added in [npm](https://npmjs.org/package/backbone-associations)...
