### ISSUE TITLE
Incorrect logic when determining index of model in associated collection

### ISSUE THREAD

**Issue by ralfthewise** [dhruvaray/backbone-associations#25]
The following logic appears to be wrong in the _bubbleEvent method (~line 189):

```
      return eventObject === (changedModel instanceof AssociatedModel
          || changedModel instanceof BackboneCollection)
          ? changedModel : (model.get(initialTokens) || model);
```

I will submit a pull request with what I believe is the correct logic and a unit test demonstrating the issue.

**Comment by jdkanani** [comment]
Merged pull request #26 for this issue.
