### ISSUE TITLE
 Cannot read property '_bubbleEvent' of undefined

### ISSUE THREAD

**Issue by cameronmaske** [dhruvaray/backbone-associations#27]
Hi, 
I have been getting the following error when fetching new models with a Backbone.One relation. 

Uncaught TypeError: Cannot read property '_bubbleEvent' of undefined 
 backbone-associations.js:161

I am on version 0.4.1.

I am not really sure what is causing this. How can I help to debug the problem further?

**Comment by jdkanani** [comment]
Can you please provide your example code on fiddle?

**Comment by cameronmaske** [comment]
Hey jdkanani, I found the problem was called by a Collection's comparator function retuning an undefined variable. I think this fault was caused on my side rather then from anything backbone associations did. Would you still like me to provide a code example?

**Comment by jdkanani** [comment]
Thanks @cameronmaske. And yes, it would be great if you can provide an example.

**Comment by dhruvaray** [comment]
@cameronmaske, you can pick up a wealth of examples from the [tests](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js)...
