### ISSUE TITLE
global 'change' doesn't work

### ISSUE THREAD

**Issue by cnlevy** [dhruvaray/backbone-associations#28]
it is important to note that you can't listen to associated model  changes just by having
this.on('change', callback);
You need to listen to this.on('change:associatedModel', callback)

**Comment by dhruvaray** [comment]
Can you please give an example or a jsfiddle - which demonstrates the problem you are facing? See this particular [test case](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L353-L368) (highlighted in yellow) which does both `change` and `change:AssociatedModel`

**Comment by cnlevy** [comment]
here is the jsfiddle : http://jsfiddle.net/GV4Tq
I'm talking about the case where you do : 
model.get('associatedModel').set(newAttributes)

**Comment by dhruvaray** [comment]
Thanks for clarifying. This is deliberate. The rationale for introducing _fully qualified_ paths was that the path would give you info about which node in the hierarchy has changed and you could get the info about the changed node through the event arguments.

We had deliberated about introducing the global change event - at higher levels of the object graph - a couple of times, but settled for fully qualified paths at the end. While it is not difficult to add the change you want, there are some concerns
1. It would lead to a proliferation of events. In a deeply nested model, for each layer you would have to introduce at least 2 new events : `change` + `change:attribute-name` where attribute-name would not be a fully qualified path, but an immediate attribute of the node at that level.
2. We would have to simulate the events mentioned in pt#1. When you change an attribute in `product`, you are not really changing the memory reference to `product` in `item`. Consequently we cannot delegate (leverage) Backbone base infrastructure to treat it as a `change` event. Which means we would have to write more custom code and the compactness of the implementation suffers.
3. We wouldn't want these events to bubble up the hierarchy beyond one level. As it would lead to potentially duplicate events. (As they would also get converted into fully qualified event names at higher levels)

Nonetheless, I will  update the pitfalls section of the documentation to make this explicit.

**Comment by cnlevy** [comment]
Thank you for this detailed answer, and for maintaining such a useful
extension to Backbone.Model.
In fact I had guessed that feature could be deliberate, but I wanted to
stress this point so others would not fall into the same problems I had run
into.

**Comment by dhruvaray** [comment]
I have updated (4324af7c01ce063a8f8cde592f55fd404ecf1001) the pitfalls section of the documentation and cross referenced this issue.  I am glad to hear that the extension is useful to your work. If it's possible, do share a URL. I can put up a usage list if I hear from other folks as well. And yes, don't forget to star us if you like the extension!

**Comment by dhruvaray** [comment]
With BB-Associations v0.5.0+, you can now use the nested-change event for global events. See your revised fiddle [here](http://jsfiddle.net/dhruvaray/txchA/). For rationale, you can see the nested-change section in the [event catalogue](http://dhruvaray.github.io/backbone-associations/events.html#e-catalogue) documentation.

**Comment by ghhamza** [comment]
I just test your last fiddle example using "nested-change" event and it does not work (i use v0.6.2)
