### ISSUE TITLE
Visited flag on model results in wrong toJSON method output on collection events

### ISSUE THREAD

**Issue by bernii** [dhruvaray/backbone-associations#3]
Here is a sample code reproducing the issue:

http://jsfiddle.net/LHfu4/

After simple fix:

http://jsfiddle.net/xVE5G/

**Comment by jdkanani** [comment]
Thanks !!! I have added test case and merged with master 6226ce2eb8fd312404febbe4f28428a709fb8272 .

**Comment by bernii** [comment]
Thanks! Really great work BTW!
