### ISSUE TITLE
Simple Store

### ISSUE THREAD

**Issue by jamesshannon** [dhruvaray/backbone-associations#35]
Hi. Not sure if you consider this out of your scope, but I'd like to have the ability to reference a store Collection. One of the reasons I'm checking out backbone-associations is because BBRelational's store/caching got buggily aggresive. My simpler use case here, however, is for something like a store of Options based on the id attribute.

``` javascript
var InputClass = BB.Model.extend();

var InputCollection = new BB.Collection([{id: 'text', value: 'text box', validationOptions: ...}, {id: 'select', value: 'Select Dropdown', validationOptions: ....}], { model: InputClass});

var FieldClass = new BB.AssociatedModel({
    relations: [
    { type: Backbone.One, key: 'field', relatedModel: InputClass, store: InputCollection }
    ]
});

var first = new FieldClass({name: 'First Name', type: 'text'});
var job = new FieldClass({name: 'Job', type: 'select'});
```

Basically a pretty simple setup, but all possible relatedModels will be prepopulated in a collection.

On the instantiaton's call of setAttr (around line 130), it'd check  do something like:

``` javascript
val ! instanceof AssociatedModel && store && store instanceof BB.Collection && _.isString(val) && store.get(val) && val = store.get(val);
```

it could even add back to the store afterwards if it wasn't originally found.

**Comment by dhruvaray** [comment]
Hi... This was out of scope. See issue #32 for the explanation....Could you step back a bit and explain the need for the store from an app flow perspective. It will help conceptualize a solution if we need to build one.

**Comment by jamesshannon** [comment]
That example is basically my use case.

I literally have a collection of options which I want to reference in the "parent" as just an ID. In last night's case it was a static collection of InputType models (that would describe various HTML input type elements, where they can be added, how, what validation can be presented as options, etc). I'm not even sure this will ever end up in the database (it can, but I plan on keeping it hardcoded in the javascript for now).

So, it makes sense that when you add a Field, you would associate a single InputType. And, similarly, when you fetch Fields from the database, it would only include the InputType id, which could then be used to attach the relevant InputType instance.

Somehow this seems like a simpler "store" concept to me than BB Relational.

With that being said, though, as I started working around the lack of a store and got a bit deeper (into .save()), I realized that you'd also have to support something like includeInJSON, too. Because otherwise, even if you did populate based on an ID, you would want to have the option to not send back the entire model. So, probably some scope creep there.

**Comment by dhruvaray** [comment]
Thanks for the explanation.

Now that I understand the underlying motivation better, wouldn't this achieve your needs?

``` javascript
var FieldInputType = Backbone.Model.extend({
  defaults: {
    id:"-1",
    type:"",
    source:"<div/>"
  }
});

var Field = Backbone.AssociatedModel.extend({
    relations : [{
        type : Backbone.One,
        key : 'type_layout_data',
        relatedModel : 'FieldInputType'
    }],

    defaults : {
        type_layout_data : undefined,
        type : undefined,
        data : undefined,
        name: ""
    },

    //Store at model level. Not at instance level
    type_layout_ref:new Backbone.Collection([{id:1, type:"text",source:"<input type='text'/>"},
{id:2, type:'email',source:"<input type='email'/>"}],{model:FieldInputType}),

    //Custom over-ride for James-demo to simulate a network
    sync:function (method, model, options) {
        var name = "Field"+ Math.floor((Math.random()*10)+1);
        return options.success.call(this, {
            type : "text",
            data : "value to be shown on UI",
            name : name
        }, options);
    },

    initialize : function(){

        this.on("change:type",function(){
          this.set('type_layout_data',this.type_layout_ref.findWhere({type:this.get('type')}));
        },this);

        this.set('type_layout_data',this.type_layout_ref.findWhere({type:this.get('type')}));
    }

});

```

Now that `Field` model has been set-up to have a local store + can convert id(s) to `FieldInputType`  instances, the test cases below will demonstrate how this would pan out in 3 real-life scenarios

``` javascript

//Scenario 1 : Local set/get
var second = new Field({name: 'First Name', type: 'text' });
var job    = new Field({name: 'Job'       , type: 'email'});

console.log(second.get('type_layout_data').get('source'));
console.log(job.get('type_layout_data').get('source'));

//Console output
//<input type='text'/>
//<input type='email'/>

//Scenario 2 : Over the wire set/get
var first = new Field();
first.fetch();

console.log(first.get('type_layout_data').get('source'));
//Console output
//<input type='text'/>


//Scenario 3: Set the id to a different value at a later stage
second.set('type',"email");
console.log(second.get('type_layout_data').get('source'));

//Console output
//<input type='email'/>

```

Hope that makes it clear. This also elegantly handles this concern of yours 

> I'm not even sure this will ever end up in the database (it can, but I plan on keeping it hardcoded in the javascript for >now).

**Comment by jamesshannon** [comment]
Hi. Thanks for that.

I've got to admit, I don't completely understand it (mostly exactly when the change:type event on the Field will fire in relation to when backbone associations needs type_layout_data), but I generally see what you're doing.

So, cool... like the rest of BB, it's easy enough to extend things out to support this use case, and I'll use this code as a starting point if I end up switching back to associations.

I think I was just suggesting that it's a common enough use case, and possibly within Association's scope, that there could be something like:

``` javascript
relations : [{
        type : Backbone.One,
        key : 'type',
        store: new Backbone.Collection([{id:1, type:"text",source:"<input type='text'/>"},
{id:2, type:'email',source:"<input type='email'/>"}],{model:FieldInputType}),
        relatedModel : 'FieldInputType'
    }]

```

**Comment by dhruvaray** [comment]
The change handler sets the correct reference of `type_layout_data` (from the model-level store) whenever the `type` field changes (in all the 3 scenarios I mentioned). You can copy-paste+run the example in firebug console to play around with it.

I hope that you do switch to BB-Associations for your needs. I am yet not convinced about introducing a store at the library level. (For the simple reason that I may not be able to generalize it nicely for all scenarios)

**Comment by dhruvaray** [comment]
I decided to re-visit your request and allow for a way of providing mappings (to key values) at the framework level. The mapping function can use a store internally (if necessary). This is how [your](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L624-L691) use case would look with the new API. Let me know if this works for you.

**Comment by dhruvaray** [comment]
Now part of backbone-associations v0.5.0. Do checkout the new website and features!
