### ISSUE TITLE
Question: Why are nested models always saved when parent is saved?

### ISSUE THREAD

**Issue by johanneslumpe** [dhruvaray/backbone-associations#38]
I have a hierarchy like this:

Project > Group > Task

First I create a Project, assign a Group to it, by getting the relation-object and calling add() on it. Then I assign some tasks to the group.

When i now call save() on the project, it will of course save the whole Project, including its nested models. But when I call save() on every single  task, before i call save() on the project, it will still PUT the project including all groups and tasks, even though the tasks didn't change.

isNew() on  the model reports 'false' and 'changed' is an empty object. So the model really didn't change. Why is it still being saved? Is this desired behavior? Or am I missing something?

**Comment by jdkanani** [comment]
Following code seems to be working fine. It sends only title for `task1.save`.
Could you please share your code snippet?

``` javascript
    // Initialization
    var Task = Backbone.AssociatedModel.extend({
        url: 'task',
        defaults: {
            title: undefined,
            description: undefined
        }
    });

    var Group = Backbone.AssociatedModel.extend({
        url: 'group',
        relations: [
            {
                type: Backbone.Many,
                key: 'tasks',
                relatedModel: Task
            }  
        ],
        defaults: {
            name: undefined,
            tasks: []
        }
    });

    var Project = Backbone.AssociatedModel.extend({
        url: 'project',
        relations: [
            {
                type: Backbone.Many,
                key: 'groups',
                relatedModel: Group
            }    
        ],
        defaults: {
            title: undefined,
            groups: []
        }
    });

    // Test 
    var group1 = new Group({
        name: 'group1'
    });
    var project1 = new Project({
        title: 'project1'
    });
    project1.get('groups').add(group1);

    var task1 = new Task({
        title: 'task1'
    });
    group1.get('tasks').add(task1);


    project1.save(); // POST whole project
    task1.save(); // POST only that task

    // After save
    task1.save({title: 'changedTask'});
```

For `isNew` and `changed` object:
Here, In Backbone example -- `book.save` will send 3 http requests. Not sure whether It should care about `changed` object or not.

``` javascript
// Example from Backbone docs
Backbone.sync = function(method, model) {
  console.log(method + ": " + JSON.stringify(model));
  model.id = 1;
};

var book = new Backbone.Model({
  title: "The Rough Riders",
  author: "Theodore Roosevelt"
});

book.save();
book.save(); // Added another save deliberately

book.save({author: "Teddy"});
```

**Comment by johanneslumpe** [comment]
Thank you for the quick reply! I double checked everything and you are right - the code works as you stated it would. My issue is actually what you are showing in your 2nd example. Even though book didn't change at all, a 2nd request is sent - but this is probably a backbone-issue then and not backbone-associations related.

A solution would probably be, to just overwrite the `save()` method or introduce a new `saveChanged()` method, which will only send the data which actually changed.

In regard to relations: When you save the project using `project1.save()` it will post the whole project, as you wrote. If you now change a property on your project and invoke `save()` again, it will POST the whole project again - including relations.

It might be nice to have something like this built right into backbone-associations, so that you can save a parent model, without having to save its relations, when they didn't change - thus avoiding traffic overhead. I'll test some code - maybe I can get somewhere!

**Comment by jdkanani** [comment]
You can always override `toJSON` to exclude nested model while saving,  and of course using `{patch:true}` as option.

**Comment by johanneslumpe** [comment]
True! I will give that a go - thanks!
