### ISSUE TITLE
Parent-chain behaviour issue

### ISSUE THREAD

**Issue by atomictag** [dhruvaray/backbone-associations#39]
I am experiencing some issues with broken child->parents chain in some cases.

Here's a reduced example that shows the problem:

```
var Nested = Backbone.AssociatedModel.extend();

var Child = Backbone.AssociatedModel.extend({
    relations : [{
        type: Backbone.One,
        key : 'nested',
        relatedModel: Nested
    }]
});

var Root = Backbone.AssociatedModel.extend({
   relations : [{
       type: Backbone.One,
       key : 'child',
       relatedModel: Child
   }, {
       type: Backbone.One,
       key : 'nested',
       relatedModel: Nested
  }]
});

var root = new Root;
var child  = new Child;

// Add 'nested' to root model
root.set('nested', new Nested);
console.assert(root.get('nested').parents[0] === root, 'not ok');

// Add 'nested' to child model
child.set('nested', new Nested);
console.assert(child.get('nested').parents[0] === child, 'not ok');

// Add child to parent
root.set('child', child);
console.assert(root.get('nested').parents[0] === root, 'not ok'); // <= this will assert
```

The culprit seems to be this line:

https://github.com/dhruvaray/backbone-associations/blob/master/backbone-associations.js#L170

I can't really figure out what the intended purpose of removing the current model from the parent list of one of its attributes is:

```
original.parents = _.difference(original.parents, [this]); // Line 170
```

If I comment this out everything works as expected, but I am not sure this does not produce unwanted side-effects elsewhere.

Thanks!

**Comment by dhruvaray** [comment]
Thank you for using the new feature from the edge version and the bug contribution! The issue has now been fixed. I have added your test case to the test suite as well. 

In short, the fix needed to distinguish between an `undefined` value being set versus not passing in any value for that attribute. As an aside, the `_.difference` call is important (see the prior test case in the suite for why so)

While we are on the topic, please let us know whether you find the idea of implicit reverse relations useful for your application.

**Comment by atomictag** [comment]
Thanks for this - that's great. I have been using Backbone Associations for a while now and I am very happy with it. Just wanted to give a shot to this new feature - and then this issue came out on an application I have built.
Regarding the feature per-se I am still trying to make up my mind on whether it would be useful or not - given the good and simple event bubbling that comes out of the box with BA. The only use cases I came out with so far are:
- a child that needs to subscribe to events issued by the parent(s)
- a child that needs to read some properties from its parent (for example, the parent "id" property before performing a fetch - or to compose its url() )

All in all it's a nice to have feature - I think Backbone.Relational offers something similar so there are perhaps real-life cases where people are using this in the wild, which would make transitioning to Associations easier.

For me it's key that, by design, a related model can have multiple parents, as I tend to build fairly large trees of models in which the same model instances may appear many times in different branches of the tree. I was glad to see BA does exactly that!

BTW, I have worked out an extension of Associations that allows auto-fetching and resolution of related models - in order to get a fully denormalized tree of nested associated models/collections (each one with its own server-side resource representation) with a single fetchAll/fetchRelated call on the root node - which also takes into account duplications and relayouting of the tree as it gets populated. At some point I might publish it somewhere so you could have a look (it does not require any changes to the core Backbone.Associations).

Keep up with the good work

**Comment by dhruvaray** [comment]
Wonderful... I am going to bump up the minor version tag soon to announce this feature. I am very pleased to hear that backbone-associations has worked well for you! Please do drop a note whenever you release your extension and we will take a look as well. You were bang on the target behind our key motivations for BA. For a more detailed  perspective, you may want to stop by #32

Thanks once again!

**Comment by atomictag** [comment]
Super. Your fix did the trick. Thanks a lot.

**Comment by dhruvaray** [comment]
@atomictag : you may want to update your app code to prevent potentially wrong values and a memory leak while using parents property and if you set model instances to falsy values explicitly... See [this](http://dhruvaray.github.io/backbone-associations/specify-associations.html#sa-reverse) for an explanation.

**Comment by atomictag** [comment]
Will keep this in mind. Thanks for the heads up!
