### ISSUE TITLE
IE8 does not natively support [].indexOf, any reason not to use underscores implementation?

### ISSUE THREAD

**Issue by jballant** [dhruvaray/backbone-associations#42]
I wanted to make an app that's backwards-compatible with IE8, but I am getting fatal error loading up backbone-associations because on line 179 it use the native indexOf method on an array:

```
(updated.parents.indexOf(this) == -1) && updated.parents.push(this);
```

This method doesn't exist in IE8, so I was wondering if it would be possible to use underscore's indexOf implementation, which uses the native version if it exists. It seems that I am able to get backbone-associations to work in IE8 simply changing line 179 to this:

```
 (_.indexOf(updated.parents, this) == -1) && updated.parents.push(this);
```

Just wondering, is there a reason this wasn't done? Perhaps there are other more substantial issues with trying to support IE, but on the surface this seems like a worthwhile change.

P.S. thanks so much for this extension.

**Comment by dhruvaray** [comment]
Thanks for catching this! It was an oversight. The change is now pushed to the repo. I am glad to hear that the extension is useful for you.

**Comment by jballant** [comment]
Great, thanks!
