### ISSUE TITLE
Fetch parent model and triggering a reset on child collections

### ISSUE THREAD

**Issue by chiplay** [dhruvaray/backbone-associations#45]
I have a parent model, SearchResults, that has a 1-to-M relationship to a ProductsCollection and a 1-to-1 relationship to a SearchFacet model.  The SearchFacet model is a parent of four 1-to-M collections, Categories, Brands, Vendors, Tags.

When I run a fetch on the SearchResults model, the results from the server are "set" on the child collections, but I need a way to treat them as a "reset".  I need the server data from the fetch to completely overwrite the full set of parent and child models / collection.

Is this possilble?  Or should I simply unset the parent SearchResults model before each new fetch?

**Comment by jdkanani** [comment]
You can now use `reset` option to reset nested collection. `searchResult.fetch({reset: true})`.
I have added your example as a test case [here](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L774-L899).

**Comment by dhruvaray** [comment]
@hybriddesign : Thanks for catching this! We missed this scenario.

**Comment by chiplay** [comment]
Thanks for the quick patch - awesome!
