### ISSUE TITLE
Getting attribute "key" of an associated child collection

### ISSUE THREAD

**Issue by chiplay** [dhruvaray/backbone-associations#46]
Is there is a simple way to retreive the attribute "key" of a child collection from a parent model? I have a view that gets fed a dynamic collection, that is a child of a model.  I need to use the attribute key in a conditional - but not sure how to best access it directly from the child collection.  I can get the parent model using childCollection.parents[0], but this doesn't give me the key.  Thanks for your help!

**Comment by dhruvaray** [comment]
If I understand you correctly, Is this what you are looking for?

``` javascript
value = childCollection.parents[0];
_.find(value.attributes,function(attribute){return value[attribute] === childCollection)});
```
