### ISSUE TITLE
Events stop bubbling after a fetch

### ISSUE THREAD

**Issue by filR** [dhruvaray/backbone-associations#47]
Setting up a collection with listener:

``` javascript
var f = new FCollection();
f.on('add', function (e) { .. } );
f.fetch();
f.at(0).get('xxx').add({});
```

Leads to the event `add:xxx` being triggered on f. w00t.

However, after **another `f.fetch()`, adding models no longer triggers an event on f.** If a reset is forced with `f.fetch({ reset: true })`, the events bubble up to f again, but this resets the models within f, which doesn't work in my scenario (each of these models is hooked up in it's own view).

Is this working as intended? Am I doing something wrong?

The relation defintion within f && JSON from the server:

``` javascript
relations: [{
    type: Backbone.Many,
    key: 'xxx',
    relatedModel: 'TS.UserModel'
}]
```

``` javascript
[{
    "id": 468,
    "name": "I am so cool",
    "xxx": [{
        "id": 415,
        "email": "art@garfunkel.com"
    }]
}]
```

ps // Thanks for this awesome lib.

**Comment by dhruvaray** [comment]
Thanks for catching this. Your scenario is now part of the test suite. You can check it out [here](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L822-L880).

Thanks for the compliment too! Don't forget to star us if you like our work!

**Comment by filR** [comment]
Wow, thanks for the fast reply. I can confirm that your commit solves the problem. _thumbsup_
