### ISSUE TITLE
AMD and self-referencing

### ISSUE THREAD

**Issue by MatBart** [dhruvaray/backbone-associations#48]
I use backbone-associations in a AMD requirejs application, that's working fine with your recipe.

But i want to set a relation with the same model (friends from user).
How can I achieve this ?

In your example of model related to the same model, you set relatedModel as a string and not the class directly. But how can I do this in AMD ?

**Comment by jdkanani** [comment]
We are introducing `Backbone.Self` to resolve this scope problem. [Here](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L1420-L1453) is test case to show how it can be used.

``` javascript
var User = Backbone.AssociatedModel.extend({
    relations: [
        {
            key: 'friends',
            type: Backbone.Many,
            relatedModel: Backbone.Self
        }
    ],
    defaults: {
        username: undefined,
        fname: '',
        lname: '',
        aboutMe: '',
        friends: []
    }
});

var user = new User({username: 'user1', friends: [{username: 'user2'}]});
```
