### ISSUE TITLE
collectionType benefits ?

### ISSUE THREAD

**Issue by sdeleuze** [dhruvaray/backbone-associations#52]
First thanks for this awesome lib !!!

My question is: since collectionType is optional, could you explain in a more detailed way when we should use it ? It may be a useful documentation update.

**Comment by jdkanani** [comment]
There are a number of built-in/custom properties we can define for collection using `collectionType`, such as`parse`, `comparator` or even `url`.

``` javascript
var Chapter = Backbone.AssociatedModel.extend({
     defaults: {
        page: 0,
        title: ''
     }
});
var Chapters = Backbone.Collection.extend({
    comparator: function(c){
        return c.get('number');
    },
    model: Chapter
});
var Book = Backbone.AssociatedModel.extend({    
    relations: [
        {
            type: Backbone.Many,
            key: 'chapters',
            collectionType: Chapters

           //No need to defined relatedModel if collectionType is available. (Added for simplicity)
            relatedModel:  Chapter          
        }
    ],
    defaults: {
        name: '',
        author: '',
        chapters: []
    }
});
```

These could also be useful for Backbone-paginator or even custom pagination. Hope this helps!

**Comment by dhruvaray** [comment]
@jdkanani : Thanks! @sdeleuze : Will update the documentation for the upcoming v0.5.1 release

**Comment by sdeleuze** [comment]
Thanks
