### ISSUE TITLE
Nested relationships fail to serialize inside Backbone.Self toJSON

### ISSUE THREAD

**Issue by chiplay** [dhruvaray/backbone-associations#56]
When you create a Backbone.Self relationship, and that model has its own associations, the toJSON fails to serialize the nested models.  

Example:

```
var Brand = Backbone.AssociatedModel.extend({
  defaults: {
    name: null
  }
});

var Product = Backbone.AssociatedModel.extend({
  relations: [
    {
      type: Backbone.One,
      key: "brand",
      relatedModel: Brand
    },
    {
      type: Backbone.One,
      key: "alternate",
      relatedModel: Backbone.Self
    }
  ]
});

var banana = new Product({id:1, alternate:{id:2, alternate: null, name:"Peach", brand: {id: 1, name: "Dole"} }, name:"Banana", brand:{id:1, name: "Chiquita"} });
```

When you try to access alternate.brand.name in an underscore template it fails, as "brand" has not been serialized to an object.

I might be missing something - thanks in advance for the help!

**Comment by jdkanani** [comment]
I am not sure if I understood it correctly, but underscore template and serialization are working fine.
Here is an example:

``` javascript
var templateStr = "Alternate product: <%=alternate.name%>,  Brand: <%=alternate.brand.name%>";
_.template(templateStr, banana.toJSON()); //=> Alternate product: Peach,  Brand: Dole
```

**Comment by dhruvaray** [comment]
Closing... Since I haven't heard back from @hybriddesign
