### ISSUE TITLE
errors for required options

### ISSUE THREAD

**Issue by kosmotaur** [dhruvaray/backbone-associations#57]
Hi,

I've just spent around 3 hours debugging because I habitually entered `typeof` instead of `type` in my relation config. I had to follow execution deep into the library's code to spot that.

If you specify in docs that something is required, and the required option is not provided, please be more strict about it and throw some informative errors. Otherwise people will get silent failures, which is a nasty scenario to debug. Thanks.

**Comment by dhruvaray** [comment]
@kosmotaur : I agree and apologize for the pain.

This commit - e3ccda0 - beefs up the error handling and would have caught your typo. This [test case](https://github.com/dhruvaray/backbone-associations/commit/e3ccda0d57e01f7350dee4e0afd4e6d7e19ea677#L1R368) demonstrates what all error scenarios are handled with this commit.

**Comment by kosmotaur** [comment]
@dhruvaray hey no worries, and great you've already fixed it, thanks!
