### ISSUE TITLE
Calling toJSON whilst _processPendingEvents is running returns undefined

### ISSUE THREAD

**Issue by omichowdhury** [dhruvaray/backbone-associations#58]
Hi,

If the events that are being processed call toJSON then the call to toJSON fails because this.visited is true. 

I assume the reuse of this variable name is not intentional. Changing this.visited to this.eventsVisited in _processPendingEvents fixes the issue and doesn't break any tests

Omi

**Comment by dhruvaray** [comment]
@omichowdhury : You are right...The variable name change should do the trick. It would be great if you can add a test case to the suite @ /test/associated-model.js) to demonstrate the bug so that this does not regress again. Then, I can accept the pull request.

**Comment by dhruvaray** [comment]
@omichowdhury : Just checking to find out if you are yet interested in submitting the test case?

**Comment by omichowdhury** [comment]
Yes, I am - been busy at work sorry.
I did have a quick look at it though and it wasn't immediately obvious to
me how to force the case.
I need to have _deferEvents set to true when I trigger the event, which
means I need to get to either line 188 or line line 208.
Could you give an example of what sort of association is handled by those
cases?

**Comment by dhruvaray** [comment]
No issues... This commit - af97cdd467861fe83081797a23376ca014ea1a14 - should fix the issue.
The corresponding test case is [here](https://github.com/dhruvaray/backbone-associations/commit/af97cdd467861fe83081797a23376ca014ea1a14#L1R2182).
