### ISSUE TITLE
generating models/collections with fetch()

### ISSUE THREAD

**Issue by donnut** [dhruvaray/backbone-associations#6]
Suppose there are three models; app, panel and master. app hasOne panel and panel hasMany masters. A server call with fetch returns 

```
{
    name: 'application',
    panel: {
      name: 'main panel',
      masters: [{
        name: 'header'
      },{
        name: 'footer'
      }]
    }
 }
```

How can I create a app instance, a panel instance and two master instances?
In the test file I noticed it can be done with the 'company' test, but I can not get the third level (= masters) instanciated. Should I write a dedicated parse function?

**Comment by jdkanani** [comment]
No need to write parse function.
You always write like -

``` javascript
var Master = Backbone.AssociatedModel.extend({      
    defaults : {
       name : ''                 
    }
});  
var Panel = Backbone.AssociatedModel.extend({    
    relations: [
        {
            type: Backbone.Many,
            key: 'masters',
            relatedModel: Master
        }
    ],        
    defaults: {
        name : ''     
    }       
});
var App= Backbone.AssociatedModel.extend({
    relations: [
        {
            type: Backbone.One,
            key: 'panel',
            relatedModel: Panel
        }
    ],
    defaults : {
       name : ''                 
    }
});
var app= new App({
    name: 'application',
    panel: {
      name: 'main panel',
      masters: [{
        name: 'header'
      },{
        name: 'footer'
      }]
    }
});
```

And, by comparing your scenario with test cases - 
`Employee` works for `Department` which has many `Project` and `Location`.

**Comment by donnut** [comment]
Thanks,
This is what I tried, except I had additionally defined MasterCollection and specified it as collectionType in Panel. Thus:

```
var MasterCollection = Backbone.Collection.extend({
  model: Master
})
```

and in Panel:

```
var Panel = Backbone.AssociatedModel.extend({
  ...
  relations: [{
    type: Backbone.Many,
    key: 'masters',
    relatedModel: Master,
    collectionType: MasterCollection
  }]
});
```

This results in an error:

```
Died on test #1: this.model is not a constructor - {
....
```

When the collectionType is replaced by the string 'MasterCollection' it give the error

```
Died on test #1: MasterCollection is not defined - {
...
```

When collectionType is removed from Panel, it seems to work fine.
What am I doing wrong here?

**Comment by jdkanani** [comment]
It is working for me with `MasterCollection`. It looks like - `MasterCollection` is in different scope then the scope in which you are using.

**Comment by donnut** [comment]
I've created a gist at git://gist.github.com/3938319.git
If the collectionType is activated (is now commented out), the error occurs

**Comment by donnut** [comment]
Sorry, I meant https://gist.github.com/3938319

**Comment by jdkanani** [comment]
Yes, that is fine.

Always define `Model` before `Collection`, otherwise `model` property in `Collection` will be `undefined`.
It is true for `Backbone.Model` and `Backbone.Collection` also - 

``` javascript
Master = Backbone.Model.extend({
    defaults: {
      name: 'Meester'
    }
});

MasterCollection = Backbone.Collection.extend({
    model: Master
});
```

Now, second thing - 

``` javascript
$(document).ready(function() {
  var Master = Backbone.AssociatedModel.extend({
    defaults: {
      name: 'Meester'
    }
  });

  var MasterCollection = Backbone.Collection.extend({
    model: Master
  });
...
```

is not the same scope as 

``` javascript
test('koppel modellen', function() {
    app.set({panel:panel});
    panel.set({master: [header, footer] });
    equal(app.get('panel').get('name'), 'hoofdpaneel');
    equal(app.get('panel').get('master').pop().get('name'), 'bodem');
    equal(app.get('panel').get('master').pop().get('name'), 'kop');
  });
```

define your `Model` in window scope or define namespace.

For working gist, check this out- https://gist.github.com/3938577

**Comment by donnut** [comment]
Great, thanks.
