### ISSUE TITLE
Include options in nested-change events?

### ISSUE THREAD

**Issue by jksmithing** [dhruvaray/backbone-associations#60]
Is there a reason why the options passed to `set` aren't passed as an argument to `nested-change` callbacks?

I just added `, args[2]`:

``` javascript
this.trigger.apply(this, ["nested-change", eventPath, args[1], args[2]]);
```

**Comment by dhruvaray** [comment]
Passing options would keep the events API consistent. Your code is good except for a small check to args[2]. BB-Associations now passes options to nested-change events via commit ee5e1ee
