### ISSUE TITLE
Object has no method '_processPendingEvents'  with PageableCollection

### ISSUE THREAD

**Issue by josx** [dhruvaray/backbone-associations#61]
I am trying to use Backbone-Associations with [Backbone-Pageable](https://github.com/wyuenho/backbone-pageable)

My collections extends from PageableCollections instead Backbone.Collection (if I extend from Backbone.Collection dont give me this error).

```
Model = Backbone.AssociatedModel.extend({
    idAttribute: '_id',
...
Collection = PageableCollection.extend({
     model: Model
...
```

The problem arise when `collection.fetch()` gives me
**Uncaught TypeError: Object [object Object] has no method '_processPendingEvents'**

Any clue to fix this?

**Comment by dhruvaray** [comment]
I haven't really played around with Backbone-pageable. But since, we proxy the collection methods, I suspect, it may be an ordering issue

Can you confirm that the way you load the scripts is in this order

``` html
<script src="underscore.js"></script>
<script src="backbone.js"></script>
<script src="backbone-associations.js"></script> <!-- Load bb-associations ahead of pageable -->
<script src="backbone-pageable.js"></script>

```

**Comment by josx** [comment]
@dhruvaray  You were right! Great Thanks!

**Comment by dhruvaray** [comment]
@josx : Great to hear that. Here is one important issue of backbone-pageable you should be aware of :  https://github.com/wyuenho/backbone-pageable/issues/109

It could trip up in unexpected ways.

And again, if you like our library, don't forget to star us!

**Comment by josx** [comment]
@dhruvaray  thanks for advice! 
Already starred backbone-associations ...
