### ISSUE TITLE
"parents" property not built after page reload.

### ISSUE THREAD

**Issue by pardo-bsso** [dhruvaray/backbone-associations#62]
Hi all,
are evaluating a migration from Relational to Associations. Our current setup uses git version 2a88c59532aa5ad14a2f6a9956855f6a1cd229b5.

What we see is that the parents property is populated but after reloading the page it is empty.

Is that the expected behaviour?

**Comment by dhruvaray** [comment]
It should have nothing to do with page reload... Can you share a snippet to demonstrate what you are experiencing?

**Comment by pardo-bsso** [comment]
Hi dhruvaray, thanks for your prompt response.

Well, it's a bit hard to crop our app to a minimal case so I'll try to explain myself better.
Our stack consists now of Backbone.io , visual search , associations and backbone-pageable.

the model definitions are at:
https://github.com/inaes-tic/mbc-common/blob/bb-assoc/models/Media.js

I create and fill a Media.Playlist. Then we create some Media.Ocurrence. At that point if I do from the inspector console

> > playlist1 = Universe.models[0]
> > playlist1.parents
> > [child, child, child]

where each child is an Media.Occurrence. So far so good, it works as we expect.
Now, if I reload the page and repeat the same commands at the console I get an empty array and that is what's puzzling me.

**Comment by dhruvaray** [comment]
I need to take a closer look at your code. But just so that we are on the same page - when you say - "reload the page", are you recreating the Media.Playlist and Occurence items on reload - just like the first time around? Or is there something different happening on the re-load?

**Comment by dhruvaray** [comment]
Your model definitions seem fine. I could not find any reference to parents in your project. Also, can I ask you the scenario which is forcing you to use the parents property? I think you will have to either write out a jsfiddle or abstract your scenario to get a faster turn-around.

**Comment by pardo-bsso** [comment]
Hi again, thanks for your time.

When I say "reload" I mean pressing F5 on the browser, and we get again the models from the server.

As for the parents property it is not yet there. What we want to do is to know if for a given Playlist there are Occurrences, that works as long as we do not reload the page. I'll try to make a fiddle, we were bitten in the past with small things like the loading order.

**Comment by pardo-bsso** [comment]
Hi again, thanks for your time.

When I say 'reload' I mean pressing F5 on the browser so I get again the models from the server. As for the parents property it is not yet there. What we want to do is to know if for a given Playlist there are Occurrences and that property seemed like the correct way to go. It works fine for models just created from the console but does not when fetching them from the server.

I'll try to make a fiddle, in the past we were bitten by small things like the loading order of scripts, so that exercise may uncover other bugs (and perhaps solve this situation).

Thanks

**Comment by dhruvaray** [comment]
Seems like an application problem. Clone our repository and run our test suite @ test/test-suite.html. We have a parents test case : ./test/test-suite.html?testNumber=53. If you re-run (or re-load) this multiple times in your browser, the asserts on the `parents` property works fine.

**Comment by dhruvaray** [comment]
I am closing this. Please open if you yet see a different behavior.
