### ISSUE TITLE
Comparison with DeepModel

### ISSUE THREAD

**Issue by geekdave** [dhruvaray/backbone-associations#63]
Hello!  Just stumbled upon this library, and saw lots of praise for it.  

We originally started with [Backbone.Nested](https://github.com/afeld/backbone-nested) but then it became incompatible with newer versions of Backbone.

We then switched to [DeepModel](https://github.com/powmedia/backbone-deep-model) and have been mostly happy despite a few quirks.

Just wondering if anyone could help to highlight any major differences between DeepModel and backbone-associations.  I'm curious about ease-of-use, bugs, cpu/memory usage, etc.

Having this info in the README might be a good way to help newcomers to decide which lib is best for them.

**Comment by dhruvaray** [comment]
I think an independent and unbiased assessment by real users of both the libraries would be ideal! There has been - in the past - some discussions comparing BB-Associations with BB-Relational in issue #32 and issue #55 - which covers philosophy differences and feature sets.

**Comment by dhruvaray** [comment]
@geekdave : Maybe you can share your quirks and I can comment if BB-Associations has them or not?

**Comment by geekdave** [comment]
Off the top of my head, the only one I remember was how to deal with Model keys that had a "dot" in the name.  But this was [recently fixed](https://github.com/powmedia/backbone-deep-model/pull/15), albeit in a "global way", not per-model as we had hoped.

I guess I'm more curious if there are any monsters lurking in the shadows, with regards to performance, stability, etc.  Basically any really compelling reasons that caused others to switch.  I'm going to close this for now, but if anyone has any insight to offer, please do chime in!

Thanks @dhruvaray for linking those other discussions.

**Comment by dhruvaray** [comment]
BB-Associations does not allow . in the key name as it is a path separator

**Comment by dhruvaray** [comment]
This feature is now added via issue #68 and is available in v0.5.3+
