### ISSUE TITLE
Support for Backbone 1.0 (bower config)

### ISSUE THREAD

**Issue by frekw** [dhruvaray/backbone-associations#65]
Hi,

Backbone Associations currently doesn't indicate support for Backbone 1.0. There shouldn't really be any changes that should affect this project (except for maybe the changes to model validation).

I'm using it right now together with Backbone 1.0, but it would be nice to get rid of the error messages from Bower.

**Comment by dhruvaray** [comment]
BB Associations fully supports Backbone v1.0.0. I thought the bower file spelt out the min supported version. In any case, I have updated the file just now.

**Comment by dhruvaray** [comment]
I am closing this issue... If you yet face a problem, do write back. Also, if you like our library, do show your appreciation by starring us!

**Comment by frekw** [comment]
Thanks for your help!
