### ISSUE TITLE
AssociatedModel with attributes containing a dot (period)

### ISSUE THREAD

**Issue by mattcroberts** [dhruvaray/backbone-associations#68]
I've been using backbone-associations for a while now and its generally quite helpful, but is it now impossible to have attribute names with dots in them?

For example

``` javascript
model.set("my.attribute", 123);
```

**Comment by jdkanani** [comment]
Thanks @mattcroberts 

I've added global `Backbone.Associations.SEPARATOR` property to define your own separator.
Default separator is `.`

This is small piece of code to start with:

``` javascript
Backbone.Associations.SEPARATOR = "~";
employee.set("address~zip", 91104);
```

Of course, decide your separator and stick with that through out your application to avoid complexity.

Let me know if this works for you.

**Comment by mattcroberts** [comment]
Just gave this a quick test, looks good to me. Thanks for the quick work!
