### ISSUE TITLE
1:1 relations with non Backbone objects

### ISSUE THREAD

**Issue by gregtillbrook** [dhruvaray/backbone-associations#69]
Id really like to create some relations with objects that aren't Backbone.Models. My particular use case is initialising dates with the awesome 'moment' library (http://momentjs.com/) and it'd be way cleaner if I could specify something like;

``` javascript
 {
   type: Backbone.One,
   key: 'created_at',
   relatedObject: moment
}
```

Any chance of making something like that possible?

**Comment by dhruvaray** [comment]
This particular case can be easily handled via regular Backbone attributes itself. You can run the code snippet below in a Firebug console

``` javascript
include('http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.2.1/moment.min.js')
var Comment = Backbone.AssociatedModel.extend({});
var Post = Backbone.AssociatedModel.extend({
    relations:[
        {
            type:Backbone.Many,
            key:'comments',
            relatedModel:Comment
        }
    ],
    defaults:{
        at:null,
        body:'',
        comments:[]
    },
});

var p = new Post();
p.set('at',moment().format("MMM Do YY"));

console.log(p.get('at'));
//Sep 24th 13
```

Is this what you are looking for?

**Comment by gregtillbrook** [comment]
Its more about being able to store data as a custom data type. To extend your example, if we can store data as a particular type;

``` javascript
var Comment  = Backbone.AssociatedModel.extend({
   relations:[{
      type:Backbone.One,
      key:'created_at',
      relatedModel:moment
   }],
   defaults:{
      text:''
   }
});
```

It makes it elegant to work with later like this;

``` javascript
var delta = comment1.get('created_at').diff( comment2.get('created_at') );
console.log(comment1.get('created_at').format("MMM Do YY"))
```

Now, I know I could manually set that up in the initialize method (and infact am doing so already in our code) but we have dates in multiple places + have other custom data types, so i'm hoping to avoid that kind of boilterplate/duplication.

It would also mean that updates to date values could be taken care of without more bespoke code to handle that too.

**Comment by bryanaka** [comment]
I would say this is probably a better candidate for creating a custom setter, and not a relation. This is just a rough estimate of how this would work with Moment.

```
var Comment = Backbone.AssociatedModel.extend({
     //overriding set
     set: function(key, val, options) {
        var newVal = Moment(val);
        Comment.__super__.set.call(this, key, newVal, options);
     }
});
```

I will try to write a fiddle later when I have a bit more time.

**Comment by dhruvaray** [comment]
@gregtillbrook : I realize this is late and you may have moved on with a solution, but

``` javascript
var delta = comment1.get('created_at').diff( comment2.get('created_at') );
console.log(comment1.get('created_at').format("MMM Do YY"))
```

would be yet possible with regular atomic attributes. Why do you need to specify it in the `relations` array? The reason, I need to have the relatedModel as a Backbone.Model or Collection is to ensure event propagation (in a nested scenario), previous attributes state etc.

**Comment by dhruvaray** [comment]
Please re-open if you think this needs further clarification...
