### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by donnut** [dhruvaray/backbone-associations#7]
Tried to run the example in the README file. I run into a few issues.

First, Employee must be specified globally (in the window namespace) otherwise eval(relatedModel) in line 144 fails.

The key 'manager' (mind the typo) in the defaults section of Employee must be set null. If it is set to {}, as in the example, javascript goes wild and results in 'too much recursion'

The statement:

```
project1.get('locations').on('reset', function() {
   ...
});
```

fails if 'locations' in Project is not set to [] in the defaults section. Maybe it should be set to [] by default

**Comment by jdkanani** [comment]
Here is a caution that one should keep in mind while using cyclic object.
by making, `manager` to {} in `Employee` in default, we are actually saying - `Employee` will have default `Employee` as `manager` - which creates a cycle that is enough to make JavaScript crash.

`new Employee()` with `"manager" :  {}`  will try to create - 

``` javascript
{
   fname:"",
   manager : {
      fname : "",
      manager : {
         // and so on..
      }
      ...
   }
   ...
}
```

**Comment by jdkanani** [comment]
And of course, you need to create object before bind any events to it.

**Comment by donnut** [comment]
Ok, so the example 'Specifying One-to-One Relationship' should be:

```
var Employee = Backbone.AssociatedModel.extend({      
  relations: [
  {
    type: Backbone.One, //nature of the relationship
    key: 'manager', // attribute of Employee
    relatedModel: 'Employee' //AssociatedModel for attribute key
  }],
  defaults: {
    age : 0,
    fname : "",
    lname : "",
    manager : null
  }        
});
```

right?

**Comment by jdkanani** [comment]
Yes. That's right.
