### ISSUE TITLE
Add relations at runtime

### ISSUE THREAD

**Issue by atomictag** [dhruvaray/backbone-associations#70]
Is it advisable to add relations to an object at runtime - and is there a best practice to do that? I am currently pushing a new relation into an existing associated model instance and everything seems to work ok with events etc. but I am not sure this does not have issues or side-effects. Thanks for your feedback!

**Comment by jdkanani** [comment]
Backbone-associations does not maintain any state or data internally.
So, adding relations runtime will not cause any issues or side-effects.
But, it is _not_ advisable as it will make your application code
difficult to maintain and complex (specifically, for event binding).

I would personally suggest you not to add relations runtime unless you
_really_ need to.

Let me know if it helps.

**Comment by dhruvaray** [comment]
@atomictag : There is at least [one test case](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L1229-L1236) in the repo which does what you are talking about. It should not have side-effects. But based on your application complexity, you may have to be careful about ordering issues  as @jdkanani pointed out in an earlier comment...

**Comment by atomictag** [comment]
Thanks a lot for your help, guys. I certainly won't abuse this - but it's good to know it won't cause deeper issues.
