### ISSUE TITLE
Circular Dependencies

### ISSUE THREAD

**Issue by jayd3e** [dhruvaray/backbone-associations#74]
How does backbone-associations deal with circular dependencies?  We are trying to integrate it with our app from backbone-relational, and we're running into all of these problems where two separate modules need each other.  This was solved by lazy-loading classes in backbone-relational.  How would you solve it in backbone-associations?

**Comment by dhruvaray** [comment]
Did you look at this recipe? http://dhruvaray.github.io/backbone-associations/recipes.html#tut-rev

**Comment by joeyrobert** [comment]
Yes I saw this, question about passing a string into the relatedModel field: "A fully qualified string which can be resolved to an object type on the global scope." -- does this mean available to the model at instantiation time (var a = new ModelName()) or at creation time (var ModelName = Backbone.AssociatedModel.extend(...)).

Is the solution to put all the models on the global scope?

**Comment by dhruvaray** [comment]
@ creation time. (@ type definition - BB.AssociatedModel.extend)

That is one way to do it... Alternatively, you can define `relatedModel` as a function which will return local model definitions.

``` javascript

//Inside a function
var Zoo = Backbone.AssociatedModel.extend({
    relations: [{
        type: Backbone.Many,
        key: 'animals',
        relatedModel: function(){return Animal;}
    }],
});

var Animal = Backbone.AssociatedModel.extend({
    relations: [{
        type: Backbone.One,
        key: 'livesIn',
        relatedModel: function(){return Zoo;}
    }]
});

```

For circular relationships involving the same model, you can use Backbone.Self (See this recipe in an AMD context : http://dhruvaray.github.io/backbone-associations/recipes.html#tut-amd)

**Comment by jayd3e** [comment]
I think the global scope method is the way we're going to go.  Thanks!

**Comment by dhruvaray** [comment]
Just for completeness, In a require.js context, this is the code to handle circular dependencies

``` javascript

//House.js

/**
 * Created by matt on 10/10/13.
 */
define([
    "backbone.associations",
    "Person"
], function(Associations, Person){

    var House = Backbone.AssociatedModel.extend({
        relations:[{
            key:"person",
            type:Backbone.One,
            relatedModel: function(){ return require("Person");}
        }]
    });

    return House;
})


// Person.js //
/**
 * Created by matt on 10/10/13.
 */
define([
    "backbone.associations",
    "House"
], function(Associations, House){

    var Person = Backbone.AssociatedModel.extend({
        relations:[{
            key:"house",
            type:Backbone.One,
            relatedModel: function(){ return require("House");}
        }]
    });

    return Person;
}

```

Complete gist is here : https://gist.github.com/dhruvaray/6929867. We will eventually call this issue out as a recipe in our documentation.

**Comment by dhruvaray** [comment]
Added as a recipe to our documentation now : http://dhruvaray.github.io/backbone-associations/recipes.html#tut-rev2

**Comment by monovertex** [comment]
You should not that this is not a good approach if the developer plans to use the optimizer tool of require.js in the future, because that tool does not take `require` calls inside the modules into consideration.

In my situation I found the only way to go was with a custom global namespace. It cripples a bit the modular approach, but it was the most robust method I found, while also allowing me to use the optimizer tool.
