### ISSUE TITLE
Should there be a parse option for sub models?

### ISSUE THREAD

**Issue by donato** [dhruvaray/backbone-associations#75]
Hi dhuvaray,

For one of my projects, I recently converted from Relational to Associations.
In general the change went like so : 

Old : tableModel.set( json );
New: tableModel.set( json, {parse: true} );

With Relational, you can define a relation with the option "parse" which tells it to always parse when setting that sub-model. With associations, you need to state "parse: true" with each set, and it propagates down to all the sub models.

Was there a reason you chose not to have this option, or is it just not necessary yet?

Thanks,
Donato

**Comment by jdkanani** [comment]
You can also define `options` in relation.

``` javascript
var Employee = Backbone.AssociatedModel.extend({
    parse:function (obj) {
           if (obj.sex === "M") {
                obj.prefix = "Mr.";
           }
           return obj;
     }
});
var Company = Backbone.AssociatedModel.extend({
    relations:[
        {
            type:Backbone.Many,
            relatedModel:Employee,
            key:'employees',
            options:{
                parse:true    //  set relation options
            }
        }
    ]
)};
var c = new Company();
c.set("employees", [
    {
        name: "John",
        sex: "M"
    }
]);
console.log(c.get("employees[0].prefix")); // Mr.
```

Here is the [test case](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L2155-L2213).

Let me know if it works for you.

**Comment by dhruvaray** [comment]
@DonatoB : I am closing this issue since we haven't heard back. I hope it resolves your doubt and your need to get an explanation (expressed via twitter) Please reopen if you want any further discussion...

**Comment by dhruvaray** [comment]
Added as a recipe to our documentation : http://dhruvaray.github.io/backbone-associations/recipes.html#tut-options
