### ISSUE TITLE
Error on IE8: "Object doesn't support this action"

### ISSUE THREAD

**Issue by gdaybrice** [dhruvaray/backbone-associations#77]
Hello, I came across a JavaSript error while testing in IE8 at L51: "Object doesn't support this action"

Seems that the error is coming from `Object.defineProperty`

I'm adding the es5-shim and wondering if this is related to this issue: https://github.com/kriskowal/es5-shim/issues/5

Any possible workaround/shim available?

Thanks!
Brice

**Comment by jdkanani** [comment]
I have [fixed](https://github.com/dhruvaray/backbone-associations/commit/f8e6d712aba3fdb83662ce4dbabcf4b5da8f7445) this bug by [adding getter/setter](https://github.com/dhruvaray/backbone-associations/blob/f8e6d712aba3fdb83662ce4dbabcf4b5da8f7445/backbone-associations.js#L51-L85) for older IE versions. Please use `getSeparator` and `setSeparator` functions to set `Separator` to support IE < 9.
Also note that `SEPARATOR` property also works as expected with `Object.defineProperty` for other browsers (related to #68).

Give it a try and let me know if it works.

Thanks.

**Comment by gdaybrice** [comment]
The fix works perfectly, thanks so much Jaynti for looking at this so quickly, really appreciate it!
