### ISSUE TITLE
Documentation for map function for 1:M associations.

### ISSUE THREAD

**Issue by AlexRiedler** [dhruvaray/backbone-associations#79]
I have a 1:M association (which is based on a list of ids); I tried overwrite the mapping function but I have no clue what to expect as arguments / return value.

For instance,
sometimes I get the first argument the list: `[1,7,9]` (on parse); sometimes I get [Item(),Item(),Item()], and sometimes I get Item()

what is expected return of this mapping function? I assumed it was the 2nd argument always which is a "type function" on the first call but on the remainder of calls the collection?

related:
In the case of a collection, I though I would just add to the collection (but this causes an infinite loop, event if silent is true)

**Comment by dhruvaray** [comment]
Did you take a look at these 2 recipes? Hopefully, they should give you the answer you seek.

http://dhruvaray.github.io/backbone-associations/recipes.html#tut-map
http://dhruvaray.github.io/backbone-associations/recipes.html#tut-map2

Can you share the snippet for the infinite loop scenario?

**Comment by AlexRiedler** [comment]
I think I found a work around using the 2nd one of those; it did everything except handle one case.

My Fix was the following:

``` js
  map: function(fids, type) {
    fids = _.isArray(fids) ? fids : [fids];
    type = type instanceof Backbone.Collection ? type.model : type;
    return _.map(fids, function(fid) {
      if (fid instanceof Backbone.Model) {
        return fid;
      } else {
        return new type({
          id: fid
        });
      }
    });
```

**Comment by AlexRiedler** [comment]
After working with that code for a while, realized that does not work for when a product is added to the collection, needed this... (forgot the case where the 2nd argument happens to be the existing collection, and the first argument happens to be the newly added).

``` js
  map: function(fids, type) {
    var collection, data;
    collection = type;
    fids = _.isArray(fids) ? fids : [fids];
    type = type instanceof Backbone.Collection ? type.model : type;
    data = _.map(fids, function(fid) {
      if (fid instanceof Backbone.Model) {
        return fid;
      } else {
        return new Entities.Product({
          id: fid
        });
      }
    });
    if (collection instanceof Backbone.Collection) {
      return data;
    } else {
      return new type(data);
    }
  }
```

**Comment by dhruvaray** [comment]
Your snippet looks right and it should solve your problem... I'll pull it out into a recipe sometime soon. I am closing this question, but please feel free to reach out with any other issues you may face.
