### ISSUE TITLE
Support for alternate 'idAttribute'

### ISSUE THREAD

**Issue by chiplay** [dhruvaray/backbone-associations#80]
Many of our models use a custom 'idAttribute' to represent the model's id per [Backbone's documentation](http://backbonejs.org/#Model-idAttribute).  I just realized there is an issue with Backbone-Associations and this feature after some digging.  On line 163 you set the idKey to the idAttribute (which defaults to 'id'): 

``` javascript
idKey = currVal && currVal.idAttribute,
```

Then on line 230 you check:

``` javascript
if (currVal && data[idKey] && currVal[idKey] === data[idKey]) {
```

When you're using the default idAttribute of 'id' this works fine - as data['id'] does a lookup on the id attribute of the model.  But when using a custom idAttribute - eg. ProductId - data['ProductId'] always returns undefined.  I believe an alternate way to check would be:

``` javascript
if (currVal && data.attributes[idKey] && currVal.attributes[idKey] === data.attributes[idKey]) 
```

which should correctly resolve for both standard ids and custom idAttributes.

Thanks!

**Comment by dhruvaray** [comment]
@chiplay : My apologies for the delay as I was on a vacation. Thanks for catching this. You are right!. I have put in the fix and the corresponding test case with this commit : 649910340b95d77c97fba4eda0d0c69775c8229c. Let me know if this works for you.

**Comment by chiplay** [comment]
No worries - hope you had a good one!  That fix looks like it will do the trick. Thanks as always.

**Comment by mikemajara** [comment]
I found this problem persists in the latest version (0.6.2). I did not inspect the code thoroughly, but I see the line commited to fix this error changed. get the following error when my Model lacks an key named 'id'. Even when idAttribute is set. If I set both 'id' and idAttribute, I still get the error.

```
Uncaught TypeError: currVal._set is not a function
    at child.<anonymous> (backbone-associations.js:328)
    at underscore.js:76
    at Function._.each._.forEach (underscore.js:182)
    at child._setAttr (backbone-associations.js:260)
    at child._set (backbone-associations.js:233)
    at child.set (backbone-associations.js:197)
    at setAttr (backbone.stickit.js:267)
    at child.listener (backbone.stickit.js:177)
    at executeBound (underscore.js:758)
    at HTMLSelectElement.<anonymous> (underscore.js:771)
```

**EDIT**:
Actually, the problem seems to be in the _set method itself. When changed from ` currVal._set` to `currVal.set`, the problem disappears and `idAttribute` works fine.
