### ISSUE TITLE
Consider supporting getting/setting raw objects

### ISSUE THREAD

**Issue by Lugribossk** [dhruvaray/backbone-associations#82]
It would be nice if Associations supported setting nested raw objects, and not just nested models/collections, a la Backbone.DeepModel. That way you do not need to create models for everything deep object hierarchies, but can still use models for the places where it makes sense. Currently I'm working with some documents with deep object hierarchies and would like to move away from DeepModel to have proper types via Associations, but creating types for the entire hierarchy would be overkill for now.

If you do feel that this is out of scope for the project, I would suggest clarifying the Specify Associations - Get & Set documentation to make it clear that nested paths are only supported for models, as I initially thought that it also worked for raw objects.

**Comment by aboudreault** [comment]
+1. I just tested the same thing. Could it be possible to access raw objects the same way than model? (dot notation)

**Comment by dhruvaray** [comment]
This is not supported by Backbone-Associations in it's current form. While it is might be easy to support navigation by dot notation for nested json objects, event paths and bubbling may be non-trivial.

@Lugribossk : Why do you want to move away from DeepModel? I would like to understand your motivations before considering the feature.

**Comment by Lugribossk** [comment]
I'm working with Models that represent some complex JSON documents with a lot of nested levels of objects. Currently I'm using DeepModel to support directly getting/setting deep properties on the model, which works fine. However I'd also like to have parts of the model be properly typed Collections of Models (e.g an invoice having a Collection of InvoiceLines, rather than just a list of raw objects), so that it'll work seamlessly with the rest of Backbone (e.g. a Marionette CollectionView).

Associations looks like it will work great for this, but right now using it will mean that I have to create a lot of model classes for every level of the JSON document. But I don't really need all of those models now (and possibly not ever), so a "hybrid" solution that lets me have both typed Models/Collections and raw objects at the same time would be best.

**Comment by aboudreault** [comment]
I have the same need. Something, the reprensentation of a model can have some deep attributes, but they are not necessarily an associatedmodel. We just want to thread it as usual with dot notation. Thanks

**Comment by dhruvaray** [comment]
@aboudreault : Is it just about path navigation? Or also about being able to listen to (change) events with the full path for non-AssociatedModels?

**Comment by aboudreault** [comment]
Being able to listen for events would be useful too. I suppose that this is not straightforward?

**Comment by dhruvaray** [comment]
@Lugribossk, @aboudreault : I fear this would just replicate Backbone.DeepModel

**Comment by Lugribossk** [comment]
Good point, I guess what I'm looking for is essentially one Model class that combines the features of AssociatedModel and DeepModel. Perhaps a better approach would be some way to hook the two together, so that their features don't end up being replicated, but they can still coexist?

**Comment by aboudreault** [comment]
I wanted to use Backbone-Associations rather than Backbone-relationnal due to its performance. What I'm looking for is something that combines AssociatedModel with (DeepModel or Backbone-nested).... and at the final something that is compatible with Epoxy. This would be the best backbone model stack ;)

**Comment by dhruvaray** [comment]
@Lugribossk : The way forward for you could be

``` javascript

//A DeepModel sample taken from their github repo
var model = new Backbone.DeepModel({
    id: 123,
    user: {
        type: 'Spy',
        name: {
            first: 'Sterling',
            last: 'Archer'
        }
    },
    otherSpies: [
        { name: 'Lana' },
        { name: 'Cyrril' }
    ]
});

//Create Backbone Associated Models for the sub-hierarchy you want to integrate 
//with Marionette and other frameworks - which use Backbone Model/Collection derivatives

var Name = Backbone.AssociatedModel.extend();
var User = Backbone.AssociatedModel.extend({
            relations:[
                {
                    type:Backbone.One,
                    key:'name',
                    relatedModel:Name
                }
            ]
);

var spy= new User(model.get('user'));

//Use spy in all libraries which require regular Backbone.Models

```

Similarly for your invoice and invoice lines... Try it out and let me know if this works in your scenario.

**Comment by dhruvaray** [comment]
@aboudreault : If you are coming in from Backbone.Relational, you already have the Model definitions. I would  encourage you to not mix it up with json blobs for attribute values. If you really need to do it, you can follow the approach I have suggested in the earlier comment.

**Comment by dhruvaray** [comment]
@Lugribossk : Just as a note; WIth the earlier source snippet, you have 2 sources of truth. For read-only operations, you would be fine, but for write operations, you would have to keep both models in sync.

You could do something like

``` javascript

//DeepModel changes propagated to AssociatedModel
model.bind('change:user.*', function() {spy.set(model.get('user')});

//AssociatedModel changes propagated to DeepModel
spy.on('nested-change', function(){model.set('user',spy.toJSON()});

```

Needless to say, I would love to see you move to Backbone.Associations completely by defining a couple of extra models

**Comment by Lugribossk** [comment]
@dhruvaray I'm already doing something similar with creating Collections, and then copying changes in them back into the original model. I was trying to get away from that approach by using Associations.

However that made me think of another idea. Do you think it would be possible to create an AssociatedModel subclass that automatically creates a new association when it encounters a model property that is a raw object? I.e. something like:

```
var model = new AutoAssociatedModel({
    a: {
        b: {
            c: "test"
        }
    }
});
```

Where without any explicit declaration of relations for _a_, _b_ or _c_, they would become AutoAssociatedModel instances. That would let me avoid setting up all the assications and models I don't need yet, and avoids being a clone of DeepModel functionality. Perhaps it would even be possible for me to make this extension in my own project.

**Comment by dhruvaray** [comment]
I fear it would be too much of a deviation from a code perspective... Apart from a potentially huge proliferation of model definitions across model instances. That being said, if you can submit a working PR, I would be glad to take a look.
