### ISSUE TITLE
Caching of models to prevent duplicate instances of the same model

### ISSUE THREAD

**Issue by johanneslumpe** [dhruvaray/backbone-associations#83]
Hi,

backbone-associations is working really well - thanks for that! One issue I have come across though is that if we have two entities, which both reference the same third entity, then they do not point to the same object when the entity is created.

For example:

Person "John" references House "TheHouse" as home.
Person "Mary" references House "TheHouse" as home

In this case even though both reference the same object in the backend, on the client side the object will be created twice, even though it has the same id. Am I missing something which already addresses this issue?

Right now it seems that if TheHouse would be changed on one of those person-objects, the other one would be stale. Maybe I'm just blind, but I couldn't find anything to prevent this. Please enlighten me ;)

**Update:**

Ok it seems to be pretty easy to solve by just adding an application-wide model cache, which uses the type of the associated model as key for a caching array, and then checking that array in a custom model-function on a collection. Something along the lines:

```
model: function(attrs, options) {
    var cache = app.cache['app.models.somemodel'] = app.cache['app.models.somemodel'] || {};
    if (attrs.id && cache[attrs.id]) {
      return cache[attrs.id];
    }

    var newModel = new app.models.substance(attrs, options);
    cache[attrs.id] = newModel;
    return newModel;
  },
```

Any thoughts about this? Apart from the model creation function not updating an existing model (yet).

**Comment by dhruvaray** [comment]
Thanks! As you have already pointed out in your updated answer, an application level solution is required. (Ditto for even the base Backbone framework). Your approach looks good to me...
