### ISSUE TITLE
"keySource" functionality

### ISSUE THREAD

**Issue by gorman** [dhruvaray/backbone-associations#95]
I'm coming from Backbone Relational and currently make heavy use of keySource (http://backbonerelational.org/#relations-keySource). I'm curious if there are thoughts on implementing similar functionality into Backbone Associations. My use case mirrors the documentation I linked to; my API provides "comment_ids" that I want to map to comment models and ultimately be able to access through user.get("comments") (for example).

I saw that the equivalent of keyDestination was implemented in #78 and it would be great to add an equivalent of keySource to go along with it (which was briefly mentioned in that issue).

Thanks for creating such an awesome library. I look forward to fully migrating to it!

**Comment by dhruvaray** [comment]
Thanks! I am a little uncomfortable with this feature. Wouldn't a simple `parse` override solve the problem for you?

**Comment by gorman** [comment]
The problem isn't so much re-mapping the fields (as you said, a simple parse would do the trick), it's that "comment_ids" is just an array of IDs that need to be linked up with models in other collections. It looks like Backbone Relational keeps an internal store of collections/models and is able to find the model to associate based on the collection/model ID using that internal store.

Being able to associate a collection of models by passing just the model IDs (and of course collectionType) is probably the real feature request here. I can certainly understand if it's beyond the scope of what you want to implement in Backbone Associations, as I'm guessing that internal store is a lot of what adds bulk to the BR codebase.

I did see the example of building a store manually and using a map method, but I'm worried that would end up adding a fair amount of complexity to my app. Anyhow, feel free to close out this ticket if you want.

**Comment by dhruvaray** [comment]
I don't want to go there with Backbone-associations. I want the store to be part of the application concern (management and maintenance). BB-Associations will focus only on setup of object graphs and eventing in object hierarchies (not present in BB-relational)
