### ISSUE TITLE
Alternative to includeInJSON from backbone-relational plugin?

### ISSUE THREAD

**Issue by USvER** [dhruvaray/backbone-associations#96]
I have started to port my project from backbone-relational... but can't find any way to mimic includeInJSON option
PS More info here: #97

**Comment by dhruvaray** [comment]
On the edge version, you can use the isTransient flag (introduced via issue #78  & #85)

**Comment by USvER** [comment]
Thanks... I guess this is what i needed...
I have stopped refactoring to associations plugin for now... Reading the docs didn't give me confidence that i can successfuly port my project... Key functions is missing or i just don't know how to implement them...

**Comment by USvER** [comment]
@dhruvaray I know that my #97 is a newbie question, but please can you help me to properly implement map function?
Or maybe isTransient flag will solve both issues?

**Comment by dhruvaray** [comment]
Please don't expect a drop-in replacement for Backbone-Relational. There are differences in philosophies, approach and feature sets. See #32 for further details.
