### ISSUE TITLE
Add support for changing model/collection scope

### ISSUE THREAD

**Issue by yosiat** [dhruvaray/backbone-associations#98]
Hi,

When I am using in relatedKey/collectionType with string value the map2scope function is searching those types under window (which the root in the browser).

I would like to add ability to add scopes like backbone-relational, to solve this case.

I can submit pull request, if this feature is wanted :)

**Comment by dhruvaray** [comment]
Sure... I would like to see your solution adapted to BB-Associations (non-store). Please do submit your PR!

**Comment by yosiat** [comment]
I didn't wrote the code yet :) so before I do, what do you think about this API?

``` javascript
Backbone.Associations.addScope(App.Models)
Backbone.Associations.removeScope(App.Models) => return true/false if the scope exists
```

**Comment by jdkanani** [comment]
That looks great!
You can also add `Backbone.Associations.resetScope` to remove all scopes (or may be use `removeScope` without argument to reset scopes - this may be risky). What do you think @dhruvaray?

**Comment by dhruvaray** [comment]
@jdkanani : What about something simpler like this? @yosy : Your thoughts?

``` javascript
        var scope = {};

        var User = scope.User = Backbone.AssociatedModel.extend({

        });

        var Container = scope.Container = Backbone.AssociatedModel.extend({
            relations: [
                {
                    type: Backbone.One,
                    key: 'owner',
                    relatedModel: 'User', // << Using a regular string here
                    scope: scope
                }
            ],
            defaults: {
                users: []
            }
        });

```

**Comment by yosiat** [comment]
@dhruvaray it looks pretty much long :) and the "scope" property will be the same for all of my application models.

I like my lines small as possible, I would like at top of my models file - just write one line at that's it - Backbone.Associations.addScope(MyApp.Models);

**Comment by dhruvaray** [comment]
Ok... Please do put in your PR with some test cases...

**Comment by yosiat** [comment]
@dhruvaray , I started to write my tests and then the code.. and saw there is already the feature you suggested, defining the scope in the relation.

If this is already implemented I don't see a reason for creating addScope/removeScope/resetScopes.

What do you think @dhruvaray @jdkanani ?

**Comment by dhruvaray** [comment]
I thought it would be nice to have the scope spelt out in the context of defining a relation. However, the methods you suggest would do it globally for all relations. Can both co-exist?

**Comment by yosiat** [comment]
We can say if the relation has already a scope only this scope will be searched, otherwise we will look at the scopes the user added.

**Comment by dhruvaray** [comment]
@yosy : This commit adds the search in global scopes. (with precedence to local scope) 
@jdkanani : I have kept it as a simple array for now (rather than the 3 methods). Hope that's good.

**Comment by dhruvaray** [comment]
Test case [here](https://github.com/dhruvaray/backbone-associations/blob/master/test/associated-model.js#L1270-L1322)...

**Comment by jdkanani** [comment]
@dhruvaray Looks great! An question though - Doesn't it make difficult to delete scope?

**Comment by dhruvaray** [comment]
@jdkanani : I thought about that while doing the change. Intuitively, I felt that 
- There would not be too many entries in the global scope list
- The lifetime of the scopes would be concomitant with that of the application or module
- A new module instance would add to the scopes or reset it

That being said, based on actual usage from end-users, it would be trivial to add these API(s) - should the need be felt strongly.

**Comment by jdkanani** [comment]
@dhruvaray okay. @yosy What do you think?
