### ISSUE TITLE
RelatedModel id isn't inherited on One to One relationship

### ISSUE THREAD

**Issue by yosiat** [dhruvaray/backbone-associations#99]
Hi,
I am trying to set up one to one relationship with backbone-associations,
and I can't fetch the related model, I found the reason for that, the id isn't set for my related model, so backbone returns me the root url instead of the url.

Here is some code, that reproduce it.

``` javascript
      var AModel = Backbone.AssociatedModel.extend({
          idAttribute: "Id",
          urlRoot: "http://test/a",

          defaults: {
            Value: ""
          }
      });



      var BModel = Backbone.AssociatedModel.extend({
        defaults: {
          A: null,
          Data: ""
        },


        relations: [
          {
            type: Backbone.One,
            key: 'A',
            relatedModel: 'AModel'
          }
        ]
      });

      window.testModel = new BModel({ A: 1 });

      var url = testModel.get("A").url();
      // URL is "http://test/a", and not "http://test/a/1"
     // testModel.get("A").get("Id") === undefined  => returns true
     // testModel.get("A").id === undefined  => returns true
```

Why the url of module A isn't "http://test/a/1" and is id isn't set?
Is it a bug or I am using one to one associations the wrong way?

**Comment by yosiat** [comment]
If this is a bug, I have thought a way for fixing this, after creating the relatedModel instance, we can set the id.

https://github.com/dhruvaray/backbone-associations/blob/master/backbone-associations.js#L243

``` javascript
data.setAttribute(data.idAttribute, val);
```

**Comment by jdkanani** [comment]
I think you misspelled your object here.

``` javascript
window.testModel = new BModel({ A: 1 }); // A is not object
```

It should be like:

``` javascript
 // A should be object wiht `Id` attribute
window.testModel = new BModel({ A: { Id: 1, value: "avalue" } });
// Now, it will yield true
testModel.get("A").url() === "http://test/a/1"
```

Backbone-Associations follows same convention as Backbone.
Here is simple backbone model `idAttribute` and `url` example for brevity.

``` javascript
var Model = Backbone.Model.extend({ 
    idAttribute: 'Id',
    urlRoot: 'http://test/a' 
});
var model = new Model({Id: 1});
model.url() === "http://test/a/1" // It will yield true
```

Hope it helps.

**Comment by yosiat** [comment]
@jdkanani , If you get bmodel from the server, it won't have that hierarchy, it will have only the id as string, like this -
A: "1"

**Comment by jdkanani** [comment]
For that you should use map feature of Backbone-Associations. Please refer issue: #97 
Here is the recipe what you are looking for: http://dhruvaray.github.io/backbone-associations/recipes.html#tut-map

**Comment by yosiat** [comment]
Hi @jdkanani ,
I have changed my code to use the map function, but why backbone-associations dosen't resolve this by it's own?
I really hope this pattern of :

``` javascript
relatedModel: 'X',
map: function(id) { return new X({ Id: id }); }
```

won't be repeated in my code.

**Comment by dhruvaray** [comment]
Because Backbone-Associations does not have an internal store. It leaves it for the application to manage. You can parameterize that function so that it can work in multiple contexts.
